// ============================================================
// UPGRADED 240-DAY ROADMAP — PRODUCT-COMPANY FOCUSED
// ============================================================
// Phase 1: Coding Foundations (Days 1–40)
// Phase 2: Data Handling & SQL (Days 41–80)
// Phase 3: Machine Learning Core (Days 81–130)
// Phase 4: Deep Learning & Applied AI (Days 131–165)
// Phase 5: Backend & AI Engineering (Days 166–195)
// Phase 6: Deployment & MLOps (Days 196–215)
// Phase 7: Portfolio Projects (Days 216–235)
// Phase 8: Interview & Job Launch (Days 236–240)
// ============================================================

const PHASES = [
  { name: "Coding Foundations", start: 1, end: 40 },
  { name: "Data Handling & SQL", start: 41, end: 80 },
  { name: "Machine Learning Core", start: 81, end: 130 },
  { name: "Deep Learning & Applied AI", start: 131, end: 165 },
  { name: "Backend & AI Engineering", start: 166, end: 195 },
  { name: "Deployment & MLOps", start: 196, end: 215 },
  { name: "Portfolio Projects", start: 216, end: 235 },
  { name: "Interview & Job Launch", start: 236, end: 240 },
];

const TOPICS = [
  // ── PHASE 1: Coding Foundations (Days 1–40) ──
  "Python Install, VS Code Setup, and Hello World",
  "Variables: Strings, Integers, Floats, and Booleans",
  "Input/Output: Building Interactive CLI Programs",
  "Operators: Arithmetic, Comparison, and Assignment",
  "Logical Operators: AND, OR, NOT in Conditions",
  "Lists: Indexing, Slicing, and Core Methods",
  "Dictionaries: Key-Value Pairs and Nested Data",
  "Tuples, Sets, and When to Use Each",
  "If-Else, Elif: Conditional Logic Flow",
  "For Loops: Iterating over Lists and Ranges",
  "While Loops: Break, Continue, and Loop Patterns",
  "Practice Day: 5 Loop and Condition Coding Challenges",
  "Functions: Defining, Calling, and Return Values",
  "Arguments: *args, **kwargs, and Default Parameters",
  "Scope: Global vs. Local Variables and Closures",
  "DSA: Arrays and Two-Pointer Technique (LeetCode Easy)",
  "OOP: Classes, Objects, and the self Keyword",
  "OOP: The __init__ Constructor and Instance Methods",
  "OOP: Inheritance, Polymorphism, and super()",
  "OOP: Encapsulation and Property Decorators",
  "DSA: Hash Maps and Frequency Counting (LeetCode Easy)",
  "File Handling: Reading and Writing Text and CSV Files",
  "Error Handling: Try, Except, Finally, and Custom Errors",
  "List Comprehensions: One-Line Loops and Filtering",
  "Lambda Functions and Map/Filter/Reduce",
  "Decorators: Wrapping Functions with Reusable Logic",
  "Generators: Yielding Data for Memory Efficiency",
  "DSA: Stacks and Queues with Python Lists and Deque",
  "String Methods: Parsing, Formatting, and Regex Basics",
  "Modules and Packages: Organizing Your Python Projects",
  "Virtual Environments: venv, pip freeze, requirements.txt",
  "DSA: Sorting Algorithms — Bubble, Merge, Quick Sort",
  "DSA: Binary Search on Sorted Arrays (LeetCode Easy)",
  "DSA: Linked Lists Basics and Python Implementation",
  "DSA: Recursion Fundamentals and Base Cases",
  "Debugging: Using print, breakpoints, and VS Code Debugger",
  "Clean Code: PEP 8, Naming Conventions, and Docstrings",
  "Git Basics: Init, Add, Commit, Status, and .gitignore",
  "GitHub: Creating Repos, Pushing Code, and README Writing",
  "Coding Foundations Capstone: Build a CLI Task Manager",

  // ── PHASE 2: Data Handling & SQL (Days 41–80) ──
  "NumPy: Creating 1D and 2D Arrays",
  "NumPy: Indexing, Slicing, and Fancy Indexing",
  "NumPy: Mathematical and Statistical Operations",
  "NumPy: Reshaping, Broadcasting, and Vectorization",
  "NumPy: Random Module and Synthetic Data Generation",
  "SQL: Installing PostgreSQL/MySQL and First Queries",
  "SQL: CREATE TABLE, Data Types, and Constraints",
  "SQL: INSERT, UPDATE, DELETE — CRUD Operations",
  "SQL: SELECT, WHERE, DISTINCT, and ALIASES",
  "SQL: IN, BETWEEN, LIKE, and Pattern Matching",
  "SQL: INNER JOIN — Connecting Related Tables",
  "SQL: LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN",
  "SQL: Self-Joins, Cross-Joins, and Multi-Table Queries",
  "SQL: Aggregates — COUNT, SUM, AVG, MIN, MAX",
  "SQL: GROUP BY and HAVING for Segmented Analysis",
  "SQL: Subqueries — Scalar, Row, and Table Subqueries",
  "SQL: Window Functions — ROW_NUMBER, RANK, DENSE_RANK",
  "SQL: LEAD, LAG, and Running Totals with Windows",
  "SQL: CASE WHEN, COALESCE, and NULL Handling",
  "SQL Interview Practice: 10 Real SQL Challenges",
  "Pandas: Loading CSV, Excel, and JSON Files",
  "Pandas: Head, Tail, Info, Describe — Data Audit",
  "Pandas: Selection with .loc and .iloc",
  "Pandas: Filtering DataFrames with Boolean Logic",
  "Pandas: Adding, Renaming, and Dropping Columns",
  "Pandas: Handling Missing Data — fillna, dropna, Imputation",
  "Pandas: Handling Duplicates and Data Type Conversion",
  "Pandas: String Methods and Datetime Parsing",
  "Pandas: GroupBy, Aggregation, and Multi-Indexing",
  "Pandas: Pivot Tables, Melt, and Reshaping Data",
  "Pandas: Merging and Joining DataFrames (SQL-style)",
  "Pandas: Apply, Lambda, and Custom Transformations",
  "EDA Project: Business Case Dataset Analysis (E-commerce)",
  "EDA Project: Customer Behavior Insights with Plots",
  "Matplotlib and Seaborn: Charts, Heatmaps, and Styling",
  "Pandas: Time Series Basics and Resampling",
  "EDA Mini-Project: HR Attrition Dataset Deep Dive",
  "EDA Mini-Project: Write Insights Report from Real Data",
  "Data Handling Capstone: Clean and Analyze a 10K-Row Dataset",
  "Data Handling Review: SQL + Pandas Interview Q&A Day",

  // ── PHASE 3: Machine Learning Core (Days 81–130) ──
  "Stats: Mean, Median, Mode, and Measures of Central Tendency",
  "Stats: Variance, Standard Deviation, and Data Spread",
  "Stats: Normal Distribution and Z-Scores",
  "Stats: Correlation, Covariance, and Scatter Plots",
  "Stats: Probability Basics and Bayes Theorem Intuition",
  "Stats: Hypothesis Testing and p-Values",
  "Math: Vectors, Matrices, and Linear Algebra Essentials",
  "Math: Gradient Descent — The Optimization Engine",
  "Math: Cost Functions, Convexity, and Learning Rate",
  "ML: What is Machine Learning? Types and Workflow",
  "ML: Train-Test Split and the Danger of Data Leakage",
  "ML: Feature Scaling — StandardScaler vs MinMaxScaler",
  "ML: Encoding Categorical Variables — Label vs OneHot",
  "Regression: Simple Linear Regression with scikit-learn",
  "Regression: Multiple Linear Regression and Feature Selection",
  "Regression: R-Squared, Adjusted R², and Residual Analysis",
  "Regression: Polynomial Regression and Overfitting",
  "Regression: Ridge and Lasso Regularization",
  "Classification: Logistic Regression — Theory and Code",
  "Classification: Decision Boundaries and Threshold Tuning",
  "Classification: K-Nearest Neighbors (KNN) Algorithm",
  "Classification: Naive Bayes for Text and Tabular Data",
  "Classification: Support Vector Machines (SVM) Basics",
  "Evaluation: Confusion Matrix — TP, TN, FP, FN",
  "Evaluation: Precision, Recall, and the F1-Score",
  "Evaluation: ROC Curve and AUC Score",
  "Evaluation: Cross-Validation and K-Fold Strategies",
  "Evaluation: Bias-Variance Tradeoff Explained",
  "Trees: Decision Trees — Gini Impurity and Entropy",
  "Trees: Visualizing and Pruning Decision Trees",
  "Ensembles: Random Forest — Bagging in Action",
  "Ensembles: Feature Importance and Model Interpretation",
  "Boosting: Gradient Boosting Machines (GBM) Explained",
  "Boosting: XGBoost — Install, Train, and Tune",
  "Boosting: LightGBM and CatBoost for Production Use",
  "Hyperparameters: GridSearchCV vs RandomizedSearchCV",
  "Pipelines: Building sklearn Pipelines for Clean ML Code",
  "Feature Engineering: Creating New Features from Data",
  "Feature Engineering: Handling Imbalanced Datasets (SMOTE)",
  "Unsupervised: K-Means Clustering",
  "Unsupervised: Dimensionality Reduction with PCA",
  "ML Mini-Project: Predict House Prices End-to-End",
  "ML Mini-Project: Credit Card Fraud Detection",
  "ML Mini-Project: Employee Attrition Prediction",
  "Scikit-learn: Saving and Loading Models (Joblib/Pickle)",
  "ML Capstone: Full Pipeline — Clean, Train, Evaluate, Save",
  "ML Core Review: 20 Interview Questions Practice Day",
  "ML Core Review: Whiteboard a Model Pipeline from Scratch",
  "ML Core Review: Compare 5 Models on Same Dataset",
  "ML Core Review: Write a Technical Blog Post on Your Model",

  // ── PHASE 4: Deep Learning & Applied AI (Days 131–165) ──
  "DL: The Biological vs. Artificial Neuron",
  "DL: Weights, Biases, and Activation Functions (ReLU, Sigmoid)",
  "DL: Forward Propagation Step-by-Step",
  "DL: Loss Functions — MSE, Cross-Entropy, and When to Use",
  "DL: Backpropagation and Gradient Flow",
  "DL: Optimizers — SGD, Momentum, Adam",
  "TensorFlow/Keras: Installing and First Neural Network",
  "Keras: Sequential vs Functional API",
  "Keras: Compiling with Loss, Optimizer, and Metrics",
  "Keras: Callbacks — EarlyStopping and ModelCheckpoint",
  "DL: Regularization — L2, Dropout, and Batch Normalization",
  "DL: Hyperparameter Tuning — Batch Size, LR, Epochs",
  "DL Project: Binary Classification on Tabular Data",
  "CNN: How Computers See Pixels — Image as Matrix",
  "CNN: Convolutional Layers, Kernels, and Feature Maps",
  "CNN: Pooling, Padding, Stride, and Architecture Design",
  "CNN Project: MNIST Handwritten Digit Classifier",
  "CNN: Transfer Learning with VGG16/ResNet (Pretrained Models)",
  "CNN Project: Image Classification App with Pretrained Model",
  "NLP: Text Preprocessing — Tokenization, Stopwords, Stemming",
  "NLP: Bag of Words and TF-IDF Vectorization",
  "NLP: Word Embeddings — Word2Vec and GloVe Intuition",
  "NLP: Text Classification with TF-IDF + Logistic Regression",
  "NLP: Sentiment Analysis Project — Product Reviews",
  "NLP: Intro to HuggingFace Transformers and Pretrained Models",
  "Applied AI: Using Pretrained Models for Real-World Tasks",
  "Applied AI: Model Optimization — Quantization and Pruning Basics",
  "Applied AI: Building an Inference Pipeline (Preprocessing → Predict → Postprocess)",
  "Applied AI: When to Use ML vs DL — Decision Framework",
  "DL Mini-Project: Text Classification App End-to-End",
  "DL Mini-Project: Image Classifier with Streamlit Demo",
  "DL Capstone: Choose a Problem → Train → Deploy a Model",
  "DL & Applied AI Review: 15 Interview Questions Practice",
  "DL Review: Explain CNN Architecture to a Non-Technical PM",
  "DL Review: Compare TensorFlow vs PyTorch in a Short Report",

  // ── PHASE 5: Backend & AI Engineering (Days 166–195) ──
  "Web Basics: HTTP Methods — GET, POST, PUT, DELETE",
  "FastAPI: Setup, Uvicorn, and Your First Endpoint",
  "FastAPI: Path Parameters vs Query Parameters",
  "FastAPI: Request Body, JSON Handling, and Response Models",
  "FastAPI: Auto-Generated /docs (Swagger UI)",
  "Pydantic: Data Models, Field Validation, and Custom Validators",
  "FastAPI: Dependency Injection and Middleware",
  "FastAPI: Async/Await and Background Tasks",
  "FastAPI Project: Build a /predict Endpoint for ML Model",
  "Model Serving: Preprocessing Data Inside the API",
  "Model Serving: Structured JSON Responses and Error Handling",
  "Model Serving: Input Schema Validation with Pydantic",
  "FastAPI: Authentication Basics — API Keys and OAuth2",
  "FastAPI: Logging, Environment Variables, and Config Management",
  "FastAPI: Basic Database Integration with SQLAlchemy",
  "Docker: Containers vs VMs — Why Docker Matters",
  "Docker: Writing Your First Dockerfile for a Python API",
  "Docker: Building Images, Running Containers, and Port Mapping",
  "Docker: Environment Variables and docker-compose.yml",
  "Docker Project: Containerize Your FastAPI ML App",
  "Testing: Unit Tests with Pytest — Writing Your First Tests",
  "Testing: Mocking External APIs and Model Predictions",
  "Testing: Integration Testing — Testing the Full API Flow",
  "Git Advanced: Branching, Merging, and Resolving Conflicts",
  "GitHub: Pull Requests, Code Reviews, and GitHub Actions Intro",
  "Engineering Mini-Project: Full API + Docker + Tests Pipeline",
  "Engineering: Caching Predictions with Redis Basics",
  "Engineering: Rate Limiting and API Security Best Practices",
  "Engineering: Building a Health Check and Status Dashboard",
  "Backend & AI Engineering Review: System Design Discussion",

  // ── PHASE 6: Deployment & MLOps (Days 196–215) ──
  "Cloud: Intro to AWS vs GCP vs Azure — Which to Learn",
  "Deployment: Deploy a FastAPI App to Render/Railway",
  "Deployment: Deploy to AWS EC2 with Docker",
  "Deployment: Environment Variables and Secrets in Production",
  "CI/CD: GitHub Actions — Auto-Deploy on Push",
  "CI/CD: Building a Test + Lint + Deploy Pipeline",
  "MLflow: Experiment Tracking — Setup and First Experiment",
  "MLflow: Logging Parameters, Metrics, and Artifacts",
  "MLflow: Model Registry and Version Management",
  "DVC: Data Version Control — Track Large Datasets",
  "Monitoring: Model Performance Metrics in Production",
  "Monitoring: Detecting Data Drift and Concept Drift",
  "MLOps: Model Retraining Strategy and Automation Concepts",
  "MLOps: Latency vs Accuracy — Production Tradeoffs",
  "Streamlit: Building Interactive ML Dashboards",
  "Streamlit: File Uploader + Model Prediction UI",
  "Streamlit: Connecting a Streamlit Frontend to FastAPI",
  "Deployment: Hosting Streamlit on Community Cloud",
  "Gradio: Quick ML Demos for HuggingFace Spaces",
  "Deployment & MLOps Review: Architecture Design Discussion",

  // ── PHASE 7: Portfolio Projects (Days 216–235) ──
  "Project 1: Customer Churn — Problem Statement and Dataset",
  "Project 1: Churn — Exploratory Data Analysis",
  "Project 1: Churn — Feature Engineering and Preprocessing",
  "Project 1: Churn — Model Training and Evaluation",
  "Project 1: Churn — Hyperparameter Tuning and Final Model",
  "Project 1: Churn — FastAPI Prediction Endpoint",
  "Project 1: Churn — Streamlit UI and Demo",
  "Project 1: Churn — Docker, Deploy, and GitHub README",
  "Project 2: Resume Screening NLP — Problem and Dataset",
  "Project 2: Resume Screening — Text Preprocessing and EDA",
  "Project 2: Resume Screening — TF-IDF and Model Training",
  "Project 2: Resume Screening — Ranking Logic and API",
  "Project 2: Resume Screening — UI, Deploy, and README",
  "Project 3: Sales Forecasting — Problem and Time-Series Data",
  "Project 3: Sales Forecasting — EDA and Feature Engineering",
  "Project 3: Sales Forecasting — Model Training and Evaluation",
  "Project 3: Sales Forecasting — Dashboard and Deployment",
  "Project 3: Sales Forecasting — Business Insights and README",
  "Portfolio: GitHub Profile Cleanup and Project Pinning",
  "Portfolio: Writing Resume Bullets for Each Project",

  // ── PHASE 8: Interview & Job Launch (Days 236–240) ──
  "Interview Prep: Top 20 Python Coding Questions",
  "Interview Prep: Top 15 SQL Interview Challenges",
  "Interview Prep: ML Theory and System Design Questions",
  "Interview Prep: Project Walkthrough and HR Questions",
  "Job Launch: Resume Polish, LinkedIn Posts, and Apply Strategy",
];

module.exports = { PHASES, TOPICS };
