// Phase 3: Machine Learning Core (Days 81-130)
module.exports = function (day, topic, t) {
    let theory, code, questions;

    if (t.includes('mean') && t.includes('median')) {
        theory = `**Central Tendency** measures the center of data:\n- **Mean:** Average (sum/count). Sensitive to outliers.\n- **Median:** Middle value when sorted. Robust to outliers.\n- **Mode:** Most frequent value.`;
        code = `import numpy as np\ndata = [25, 30, 35, 40, 45, 50, 200]\nprint(f"Mean: {np.mean(data):.1f}")   # pulled by 200\nprint(f"Median: {np.median(data)}")    # robust\nfrom collections import Counter\nscores = [85, 90, 85, 92, 85, 88]\nprint(f"Mode: {Counter(scores).most_common(1)[0][0]}")\n\n# When mean != median → data is skewed\nsalaries = np.random.exponential(50000, 1000)\nprint(f"\\nSalary Mean: {np.mean(salaries):.0f}")\nprint(f"Salary Median: {np.median(salaries):.0f}")\nprint("Mean > Median → right-skewed (typical for salaries)")`;
        questions = ["When is median better than mean?", "What does skewness tell you?", "Calculate mean, median, mode of a dataset.", "Why are salaries usually right-skewed?"];
    }
    else if (t.includes('variance') || t.includes('standard deviation') && t.includes('spread')) {
        theory = `**Spread** measures how data varies:\n- **Variance:** Average of squared deviations from mean\n- **Std Dev:** Square root of variance — same unit as data\n- **IQR:** Q3-Q1, used for outlier detection (1.5×IQR rule)`;
        code = `import numpy as np\nA = [48, 49, 50, 51, 52]\nB = [10, 30, 50, 70, 90]\nprint(f"A: mean={np.mean(A)}, std={np.std(A):.2f}")\nprint(f"B: mean={np.mean(B)}, std={np.std(B):.2f}")\n\n# IQR and outliers\ndata = [10,12,14,15,16,18,20,100]\nQ1, Q3 = np.percentile(data, [25, 75])\nIQR = Q3 - Q1\nlower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR\noutliers = [x for x in data if x < lower or x > upper]\nprint(f"\\nIQR: {IQR}, Outliers: {outliers}")`;
        questions = ["Difference between variance and std dev?", "How to detect outliers with IQR?", "Why divide by n-1 for sample variance?", "Dataset A has std=2, B has std=20. What does this mean?"];
    }
    else if (t.includes('normal distribution') || t.includes('z-score')) {
        theory = `**Normal Distribution:** Bell curve where 68% within 1σ, 95% within 2σ, 99.7% within 3σ.\n\n**Z-Score:** How many std devs from mean: z = (x - μ) / σ\n- z > 2 or z < -2 → potential outlier`;
        code = `import numpy as np\nnp.random.seed(42)\ndata = np.random.normal(100, 15, 1000)  # IQ scores\nprint(f"Mean: {np.mean(data):.1f}, Std: {np.std(data):.1f}")\nprint(f"Within 1σ: {np.sum(np.abs(data - np.mean(data)) < np.std(data))/len(data)*100:.1f}%")\n\n# Z-score\ndef z_score(x, data):\n    return (x - np.mean(data)) / np.std(data)\n\nfor val in [85, 100, 130, 145]:\n    z = z_score(val, data)\n    print(f"  IQ {val}: z={z:.2f} {'⚠️ outlier' if abs(z) > 2 else ''}")`;
        questions = ["What is the 68-95-99.7 rule?", "How to calculate z-score?", "When is a z-score considered an outlier?", "Why is normal distribution important in ML?"];
    }
    else if (t.includes('correlation') || t.includes('covariance')) {
        theory = `**Correlation** measures linear relationship (-1 to +1):\n- +1: perfect positive, -1: perfect negative, 0: no linear relation\n- Correlation ≠ causation!\n\n**Covariance:** Direction of relationship (not standardized)`;
        code = `import numpy as np\nnp.random.seed(42)\nhours = np.array([1,2,3,4,5,6,7,8])\nscores = hours * 10 + np.random.normal(0, 3, 8)\n\ncorr = np.corrcoef(hours, scores)[0,1]\nprint(f"Study hours vs scores correlation: {corr:.3f}")\n\n# Correlation matrix\ndata = np.column_stack([hours, scores, np.random.randn(8)])\nprint(f"\\nCorrelation matrix:\\n{np.corrcoef(data.T).round(2)}")\n\n# Key insight\nprint("\\n⚠️ Ice cream sales correlate with drownings")\nprint("   But ice cream doesn't CAUSE drowning — both caused by summer!")`;
        questions = ["Difference between correlation and covariance?", "What does correlation=0 mean?", "Why 'correlation ≠ causation'?", "Calculate correlation between two arrays."];
    }
    else if (t.includes('probability') || t.includes('bayes')) {
        theory = `**Probability:** P(A) = favorable outcomes / total outcomes\n\n**Bayes Theorem:** P(A|B) = P(B|A) × P(A) / P(B)\n- Update beliefs with new evidence\n- Foundation of Naive Bayes classifier`;
        code = `# Probability basics\nprint("=== Probability ===")\nprint(f"Coin flip: P(heads) = {1/2}")\nprint(f"Die roll P(even): {3/6}")\n\n# Bayes Theorem\nprint("\\n=== Bayes: Disease Testing ===")\nP_disease = 0.001      # 0.1% have disease\nP_pos_given_disease = 0.99  # 99% sensitivity\nP_pos_given_healthy = 0.05  # 5% false positive\nP_healthy = 1 - P_disease\n\nP_pos = P_pos_given_disease * P_disease + P_pos_given_healthy * P_healthy\nP_disease_given_pos = (P_pos_given_disease * P_disease) / P_pos\n\nprint(f"Test positive → actually sick: {P_disease_given_pos:.1%}")\nprint("Even with 99% accurate test, only ~2% chance if disease is rare!")`;
        questions = ["What is Bayes Theorem?", "Why is prior probability important?", "Explain the disease testing example.", "How is Bayes used in spam filtering?"];
    }
    else if (t.includes('hypothesis') || t.includes('p-value')) {
        theory = `**Hypothesis Testing:** Make data-driven decisions.\n- H₀ (null): No effect/difference\n- H₁ (alternative): There IS an effect\n- **p-value < 0.05** → reject H₀ (statistically significant)\n\n**A/B Testing:** Product companies use this daily.`;
        code = `import numpy as np\nfrom scipy import stats\n\n# A/B Test: Does new button color improve clicks?\nnp.random.seed(42)\ncontrol = np.random.binomial(1, 0.10, 1000)   # 10% click rate\nvariant = np.random.binomial(1, 0.12, 1000)   # 12% click rate\n\nt_stat, p_value = stats.ttest_ind(control, variant)\nprint(f"Control mean: {control.mean():.3f}")\nprint(f"Variant mean: {variant.mean():.3f}")\nprint(f"p-value: {p_value:.4f}")\nprint(f"Result: {'✅ Significant!' if p_value < 0.05 else '❌ Not significant'}")`;
        questions = ["What is a p-value?", "What is H₀ vs H₁?", "How is A/B testing used at Google/Amazon?", "What does p < 0.05 mean?"];
    }
    else if (t.includes('vector') || t.includes('linear algebra')) {
        theory = `**Linear Algebra for ML:**\n- **Vectors:** Feature arrays. Dot product measures similarity.\n- **Matrices:** Datasets are matrices (rows=samples, cols=features)\n- **Transpose:** Switch rows↔columns\n- **Matrix multiplication:** Core of neural networks`;
        code = `import numpy as np\n\n# Vectors\na = np.array([1, 2, 3])\nb = np.array([4, 5, 6])\nprint(f"Dot product: {np.dot(a, b)}")  # 32\nprint(f"Magnitude: {np.linalg.norm(a):.2f}")\n\n# Matrices\nX = np.array([[1,2],[3,4],[5,6]])  # 3 samples, 2 features\nW = np.array([[0.5],[0.3]])         # weights\nresult = X @ W  # matrix multiply\nprint(f"\\nX shape: {X.shape}")\nprint(f"W shape: {W.shape}")\nprint(f"X @ W = {result.flatten()}")  # predictions`;
        questions = ["Why is linear algebra important for ML?", "What is a dot product?", "How does matrix multiplication work?", "Explain X @ W in neural networks."];
    }
    else if (t.includes('gradient descent')) {
        theory = `**Gradient Descent:** Optimization algorithm that finds the minimum of a function.\n1. Start with random parameters\n2. Calculate gradient (slope)\n3. Update: param = param - learning_rate × gradient\n4. Repeat until convergence`;
        code = `import numpy as np\n\n# Gradient Descent: minimize f(x) = x²\ndef gradient_descent(lr=0.1, epochs=20):\n    x = 10.0  # start point\n    for i in range(epochs):\n        gradient = 2 * x  # derivative of x²\n        x = x - lr * gradient\n        if i % 5 == 0:\n            print(f"  Step {i}: x={x:.4f}, f(x)={x**2:.4f}")\n    return x\n\nprint("=== Gradient Descent ===")\nresult = gradient_descent(lr=0.1)\nprint(f"Minimum at x = {result:.6f}")\n\n# Effect of learning rate\nfor lr in [0.01, 0.1, 0.5]:\n    r = gradient_descent(lr=lr)\n    print(f"LR={lr}: converged to {r:.4f}")`;
        questions = ["What is gradient descent?", "What happens if learning rate is too large?", "What is a gradient?", "Why is gradient descent used in ML?"];
    }
    else if (t.includes('cost function') || t.includes('learning rate')) {
        theory = `**Cost Function** measures how wrong the model is:\n- **MSE** for regression: mean of (predicted - actual)²\n- **Cross-Entropy** for classification\n\n**Learning Rate:** Step size for gradient descent\n- Too small → slow convergence\n- Too large → overshooting, divergence`;
        code = `import numpy as np\n\n# MSE Cost Function\ndef mse(y_true, y_pred):\n    return np.mean((y_true - y_pred) ** 2)\n\ny_true = np.array([3, 5, 7, 9])\ny_pred = np.array([2.8, 5.2, 6.5, 9.1])\nprint(f"MSE: {mse(y_true, y_pred):.4f}")\n\n# Learning rate comparison\ndef train(lr, epochs=50):\n    w = 0.0\n    X, y = np.array([1,2,3,4,5.0]), np.array([2,4,6,8,10.0])\n    for _ in range(epochs):\n        pred = w * X\n        grad = -2 * np.mean(X * (y - pred))\n        w -= lr * grad\n    return w\n\nfor lr in [0.001, 0.01, 0.1]:\n    print(f"LR={lr}: w={train(lr):.4f} (target=2.0)")`;
        questions = ["What is a cost function?", "MSE vs Cross-Entropy: when to use each?", "What happens with wrong learning rate?", "How do cost function and gradient descent work together?"];
    }
    else if (t.includes('what is machine learning') || t.includes('types and workflow')) {
        theory = `**Machine Learning:** Algorithms that learn patterns from data.\n\n**3 Types:**\n1. **Supervised:** Labeled data → predict (regression, classification)\n2. **Unsupervised:** No labels → find patterns (clustering, PCA)\n3. **Reinforcement:** Learn from rewards\n\n**ML Workflow:** Problem → Data → EDA → Features → Train → Evaluate → Deploy`;
        code = `from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.metrics import accuracy_score\n\n# Complete ML workflow in 10 lines\ndata = load_iris()\nX_train, X_test, y_train, y_test = train_test_split(\n    data.data, data.target, test_size=0.2, random_state=42)\n\nmodel = DecisionTreeClassifier(random_state=42)\nmodel.fit(X_train, y_train)\npred = model.predict(X_test)\n\nprint(f"Accuracy: {accuracy_score(y_test, pred):.2%}")\nprint(f"Features: {data.feature_names}")\nprint(f"Target classes: {list(data.target_names)}")`;
        questions = ["3 types of ML with examples?", "What is the ML workflow?", "Supervised vs unsupervised?", "Give a real-world example of each ML type."];
    }
    else if (t.includes('train-test') || t.includes('data leakage')) {
        theory = `**Train-Test Split:** Never evaluate on training data!\n- Train: 80% — model learns\n- Test: 20% — model evaluated\n\n**Data Leakage:** When test info leaks into training.\n- Scaling BEFORE split → leakage!\n- Using future data → leakage!`;
        code = `from sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.random.randn(100, 3)\ny = (X[:, 0] > 0).astype(int)\n\n# Correct split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y)\n\nprint(f"Train: {X_train.shape}, Test: {X_test.shape}")\nprint(f"Train labels: {np.bincount(y_train)}")\nprint(f"Test labels: {np.bincount(y_test)}")\n\n# BAD: Scaling before split (leakage!)\nprint("\\n❌ BAD: Fit scaler on ALL data then split")\nprint("✅ GOOD: Split first, fit scaler on train only")`;
        questions = ["Why split data into train/test?", "What is data leakage?", "Why use stratify parameter?", "Give 3 examples of data leakage."];
    }
    else if (t.includes('feature scaling') || t.includes('standardscaler') || t.includes('minmax')) {
        theory = `**Feature Scaling** ensures all features are on same scale.\n\n- **StandardScaler:** Mean=0, Std=1 (use for most ML)\n- **MinMaxScaler:** Scale to [0,1] (use for neural networks)\n\n⚠️ Fit on train only, transform both train AND test.`;
        code = `from sklearn.preprocessing import StandardScaler, MinMaxScaler\nimport numpy as np\n\nX_train = np.array([[25, 50000], [30, 60000], [35, 80000]])\nX_test = np.array([[28, 55000]])\n\n# StandardScaler\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)  # fit on train\nX_test_scaled = scaler.transform(X_test)         # transform only\n\nprint("Before scaling:", X_train[0])\nprint("After scaling:", X_train_scaled[0].round(2))\nprint(f"Mean: {X_train_scaled.mean(axis=0).round(2)}")\nprint(f"Std: {X_train_scaled.std(axis=0).round(2)}")`;
        questions = ["Why is feature scaling needed?", "StandardScaler vs MinMaxScaler?", "Why fit only on train data?", "Which algorithms need scaling?"];
    }
    else if (t.includes('encoding') || t.includes('label vs') || t.includes('onehot')) {
        theory = `**Categorical Encoding:** ML models need numbers.\n\n- **Label Encoding:** Category → number (red=0, blue=1). Use for ordinal data.\n- **One-Hot Encoding:** Creates binary columns. Use for nominal data.\n\n⚠️ Don't use LabelEncoder for nominal data — model assumes order!`;
        code = `from sklearn.preprocessing import LabelEncoder, OneHotEncoder\nimport numpy as np\n\n# Label Encoding (ordinal)\nle = LabelEncoder()\nsizes = ['S', 'M', 'L', 'XL', 'M', 'S']\nencoded = le.fit_transform(sizes)\nprint(f"Labels: {list(zip(sizes, encoded))}")\n\n# One-Hot Encoding (nominal)\ncolors = np.array(['red', 'blue', 'green', 'red']).reshape(-1, 1)\nohe = OneHotEncoder(sparse_output=False)\nresult = ohe.fit_transform(colors)\nprint(f"\\nOne-Hot:\\n{result}")\nprint(f"Categories: {ohe.categories_[0]}")`;
        questions = ["When to use Label vs One-Hot encoding?", "Why is One-Hot better for nominal data?", "What is the dummy variable trap?", "How to handle high-cardinality categories?"];
    }
    else if (t.includes('simple linear regression')) {
        theory = `**Linear Regression:** y = mx + b\n- Finds the straight line that best fits data\n- Minimizes Sum of Squared Errors\n- Simplest and most interpretable model`;
        code = `from sklearn.linear_model import LinearRegression\nimport numpy as np\n\n# Predict salary from experience\nX = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1, 1)\ny = np.array([30, 35, 40, 50, 55, 60, 70, 75, 85, 90])\n\nmodel = LinearRegression()\nmodel.fit(X, y)\n\nprint(f"Slope (coefficient): {model.coef_[0]:.2f}")\nprint(f"Intercept: {model.intercept_:.2f}")\nprint(f"Formula: salary = {model.coef_[0]:.1f} × years + {model.intercept_:.1f}")\nprint(f"\\nPredict 12 years: ₹{model.predict([[12]])[0]:.0f}K")\nprint(f"R² Score: {model.score(X, y):.4f}")`;
        questions = ["What does linear regression find?", "What are slope and intercept?", "What does R² score mean?", "When would linear regression fail?"];
    }
    else if (t.includes('multiple linear') || t.includes('feature selection')) {
        theory = `**Multiple Linear Regression:** Multiple features predict target.\ny = b₀ + b₁x₁ + b₂x₂ + ... + bₙxₙ\n\n**Feature Selection:** Remove irrelevant features to improve model.\n- Correlation analysis\n- p-values from statsmodels\n- Feature importance from tree models`;
        code = `from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\n# Multiple features: experience, education, city\nnp.random.seed(42)\nX = np.column_stack([\n    np.random.randint(1, 15, 100),   # experience\n    np.random.randint(12, 20, 100),  # education years\n    np.random.randint(0, 3, 100),    # city tier\n])\ny = X[:,0]*6 + X[:,1]*3 + np.random.normal(0, 5, 100)\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nmodel = LinearRegression().fit(X_train, y_train)\n\nnames = ['Experience', 'Education', 'City']\nfor name, coef in zip(names, model.coef_):\n    print(f"  {name}: {coef:.2f}")\nprint(f"R²: {model.score(X_test, y_test):.3f}")`;
        questions = ["What is multiple regression?", "How to select important features?", "What is multicollinearity?", "How to interpret coefficients?"];
    }
    else if (t.includes('r-squared') || t.includes('residual')) {
        theory = `**R² Score:** % of variance explained. R²=0.85 means 85% explained.\n- 1.0 = perfect, 0 = baseline\n- **Adjusted R²**: Penalizes extra features\n\n**Residuals:** actual - predicted. Should be random with no pattern.`;
        code = `from sklearn.linear_model import LinearRegression\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.rand(100, 1) * 10\ny = 3 * X.flatten() + 7 + np.random.randn(100) * 2\n\nmodel = LinearRegression().fit(X, y)\ny_pred = model.predict(X)\n\nprint(f"R²: {model.score(X, y):.4f}")\n\n# Residual analysis\nresiduals = y - y_pred\nprint(f"Mean residual: {np.mean(residuals):.4f} (should be ~0)")\nprint(f"Std residual: {np.std(residuals):.4f}")\nprint(f"Max residual: {np.max(np.abs(residuals)):.2f}")`;
        questions = ["What does R²=0.7 mean?", "Why use adjusted R²?", "What should residuals look like?", "When is R² misleading?"];
    }
    else if (t.includes('polynomial') || t.includes('overfitting')) {
        theory = `**Polynomial Regression:** Fits curves instead of lines.\ny = b₀ + b₁x + b₂x² + b₃x³...\n\n**Overfitting:** Model memorizes training data but fails on new data.\n- High train accuracy, low test accuracy\n- Fix: simpler model, more data, regularization`;
        code = `from sklearn.preprocessing import PolynomialFeatures\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nnp.random.seed(42)\nX = np.sort(np.random.rand(50, 1) * 6, axis=0)\ny = np.sin(X).ravel() + np.random.randn(50) * 0.1\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\nfor degree in [1, 3, 15]:\n    poly = PolynomialFeatures(degree)\n    X_poly_train = poly.fit_transform(X_train)\n    X_poly_test = poly.transform(X_test)\n    model = LinearRegression().fit(X_poly_train, y_train)\n    train_r2 = model.score(X_poly_train, y_train)\n    test_r2 = model.score(X_poly_test, y_test)\n    gap = train_r2 - test_r2\n    print(f"Degree {degree:2d}: Train R²={train_r2:.3f}, Test R²={test_r2:.3f} {'⚠️ OVERFIT' if gap > 0.2 else '✅'}")`;
        questions = ["What is polynomial regression?", "What is overfitting?", "How to detect overfitting?", "3 ways to prevent overfitting."];
    }
    else if (t.includes('ridge') || t.includes('lasso') || t.includes('regularization')) {
        theory = `**Regularization** prevents overfitting by penalizing large coefficients.\n\n- **Ridge (L2):** Shrinks coefficients towards zero. Keeps all features.\n- **Lasso (L1):** Can shrink coefficients to exactly zero → feature selection!\n- **Alpha:** Controls regularization strength (higher = more penalty)`;
        code = `from sklearn.linear_model import Ridge, Lasso, LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(100, 20)  # 20 features, some irrelevant\ny = X[:, 0]*3 + X[:, 1]*2 + np.random.randn(100)*0.5\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\nfor name, model in [("Linear", LinearRegression()),\n                     ("Ridge", Ridge(alpha=1.0)),\n                     ("Lasso", Lasso(alpha=0.1))]:\n    model.fit(X_train, y_train)\n    r2 = model.score(X_test, y_test)\n    nonzero = np.sum(np.abs(model.coef_) > 0.01)\n    print(f"{name:8s}: R²={r2:.3f}, Non-zero features: {nonzero}")`;
        questions = ["What is regularization?", "Ridge vs Lasso: key difference?", "When to use Lasso?", "What does alpha control?"];
    }
    else if (t.includes('logistic regression')) {
        theory = `**Logistic Regression:** Classification using sigmoid function.\n- Output: probability between 0 and 1\n- Decision boundary at 0.5 (tunable)\n- Despite the name, it's for CLASSIFICATION not regression`;
        code = `from sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score, classification_report\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 2)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nmodel = LogisticRegression().fit(X_train, y_train)\ny_pred = model.predict(X_test)\n\nprint(f"Accuracy: {accuracy_score(y_test, y_pred):.2%}")\nprint(f"\\n{classification_report(y_test, y_pred)}")\n\n# Probability output\nprobs = model.predict_proba(X_test[:3])\nfor i, (prob, pred) in enumerate(zip(probs, y_pred[:3])):\n    print(f"Sample {i}: P(0)={prob[0]:.2f}, P(1)={prob[1]:.2f} → class {pred}")`;
        questions = ["How does logistic regression work?", "What is the sigmoid function?", "How to interpret probabilities?", "Logistic regression vs linear regression?"];
    }
    else if (t.includes('decision boundar') || t.includes('threshold')) {
        theory = `**Decision Boundary:** The line/surface that separates classes.\n\n**Threshold Tuning:** Default is 0.5. Adjust based on:\n- High threshold → fewer false positives (precision-focused)\n- Low threshold → fewer false negatives (recall-focused)`;
        code = `from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import precision_score, recall_score, f1_score\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(300, 2)\ny = (X[:, 0] + 0.5*X[:, 1] > 0.2).astype(int)\n\nmodel = LogisticRegression().fit(X, y)\nprobs = model.predict_proba(X)[:, 1]\n\nprint("Threshold | Precision | Recall | F1")\nprint("-" * 45)\nfor threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:\n    preds = (probs >= threshold).astype(int)\n    p = precision_score(y, preds)\n    r = recall_score(y, preds)\n    f = f1_score(y, preds)\n    print(f"  {threshold:.1f}     |   {p:.3f}   | {r:.3f}  | {f:.3f}")`;
        questions = ["What is a decision boundary?", "When to change threshold from 0.5?", "High precision vs high recall tradeoff?", "How to choose optimal threshold?"];
    }
    else if (t.includes('knn') || t.includes('k-nearest')) {
        theory = `**KNN:** Classify by majority vote of K nearest neighbors.\n- No training phase — stores all data\n- Distance: Euclidean, Manhattan\n- K=1: overfits. K=large: underfits\n- **Must scale features!**`;
        code = `from sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 2)\ny = (X[:, 0]**2 + X[:, 1]**2 < 1.5).astype(int)\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nscaler = StandardScaler().fit(X_train)\nX_train_s = scaler.transform(X_train)\nX_test_s = scaler.transform(X_test)\n\nfor k in [1, 3, 5, 9, 15]:\n    model = KNeighborsClassifier(n_neighbors=k).fit(X_train_s, y_train)\n    acc = accuracy_score(y_test, model.predict(X_test_s))\n    print(f"K={k:2d}: Accuracy={acc:.2%}")`;
        questions = ["How does KNN work?", "How to choose K?", "Why must KNN features be scaled?", "KNN advantages and disadvantages?"];
    }
    else if (t.includes('naive bayes')) {
        theory = `**Naive Bayes:** Fast classifier based on Bayes theorem.\n- "Naive" = assumes features are independent\n- Great for text classification (spam, sentiment)\n- Very fast, works well with small datasets`;
        code = `from sklearn.naive_bayes import GaussianNB, MultinomialNB\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\n# Gaussian NB for numeric data\nnp.random.seed(42)\nX = np.random.randn(200, 3)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nmodel = GaussianNB().fit(X_train, y_train)\nprint(f"Gaussian NB accuracy: {accuracy_score(y_test, model.predict(X_test)):.2%}")\n\n# Text classification example\nfrom sklearn.feature_extraction.text import CountVectorizer\ntexts = ["great product love it", "terrible waste money", "awesome quality", "bad broken junk"]\nlabels = [1, 0, 1, 0]\nvec = CountVectorizer().fit_transform(texts)\nmodel = MultinomialNB().fit(vec, labels)\nprint(f"Text NB classes: {model.classes_}")`;
        questions = ["Why is it called 'Naive'?", "Best use case for Naive Bayes?", "Gaussian vs Multinomial NB?", "Why is NB fast?"];
    }
    else if (t.includes('support vector') || t.includes('svm')) {
        theory = `**SVM:** Finds the hyperplane that maximally separates classes.\n- **Margin:** Distance from boundary to nearest points\n- **Kernel trick:** Map data to higher dimensions for non-linear separation\n- Works well in high dimensions, small datasets`;
        code = `from sklearn.svm import SVC\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 2)\ny = (X[:, 0]**2 + X[:, 1]**2 < 2).astype(int)  # circular boundary\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nscaler = StandardScaler().fit(X_train)\nX_tr, X_te = scaler.transform(X_train), scaler.transform(X_test)\n\nfor kernel in ['linear', 'rbf', 'poly']:\n    model = SVC(kernel=kernel).fit(X_tr, y_train)\n    acc = accuracy_score(y_test, model.predict(X_te))\n    print(f"{kernel:8s}: Accuracy={acc:.2%}")`;
        questions = ["What does SVM maximize?", "What is the kernel trick?", "When to use SVM vs other classifiers?", "Why does SVM need scaling?"];
    }
    else if (t.includes('confusion matrix')) {
        theory = `**Confusion Matrix:** Shows prediction results in a 2x2 grid.\n\n|  | Predicted + | Predicted - |\n|--|-------------|-------------|\n| Actual + | TP | FN |\n| Actual - | FP | TN |\n\n- **TP:** Correctly predicted positive\n- **FP:** False alarm (Type I error)\n- **FN:** Missed (Type II error)`;
        code = `from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay\nimport numpy as np\n\ny_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]\ny_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]\n\ncm = confusion_matrix(y_true, y_pred)\ntn, fp, fn, tp = cm.ravel()\n\nprint(f"Confusion Matrix:\\n{cm}")\nprint(f"\\nTP={tp}, TN={tn}, FP={fp}, FN={fn}")\nprint(f"Accuracy: {(tp+tn)/(tp+tn+fp+fn):.2%}")\nprint(f"Precision: {tp/(tp+fp):.2%}")\nprint(f"Recall: {tp/(tp+fn):.2%}")`;
        questions = ["What is a confusion matrix?", "What is a false positive?", "TP, TN, FP, FN — explain each.", "Why is accuracy alone not enough?"];
    }
    else if (t.includes('precision') && t.includes('recall') || t.includes('f1')) {
        theory = `**Precision:** Of all predicted positive, how many are actually positive?\n**Recall:** Of all actual positives, how many did we catch?\n**F1-Score:** Harmonic mean of precision and recall\n\n- **Spam filter:** Precision matters (don't block real email)\n- **Cancer detection:** Recall matters (don't miss cancer)`;
        code = `from sklearn.metrics import precision_score, recall_score, f1_score, classification_report\n\ny_true = [1,1,1,1,1,0,0,0,0,0]\ny_pred = [1,1,1,0,0,0,0,0,1,0]\n\nprint(f"Precision: {precision_score(y_true, y_pred):.2%}")\nprint(f"Recall: {recall_score(y_true, y_pred):.2%}")\nprint(f"F1-Score: {f1_score(y_true, y_pred):.2%}")\nprint(f"\\n{classification_report(y_true, y_pred, target_names=['Negative','Positive'])}")`;
        questions = ["Precision vs Recall: which matters more for fraud detection?", "What is the F1-score?", "When is accuracy misleading?", "High precision, low recall — what does this mean?"];
    }
    else if (t.includes('roc') || t.includes('auc')) {
        theory = `**ROC Curve:** Plots True Positive Rate vs False Positive Rate at every threshold.\n\n**AUC (Area Under Curve):** Overall model quality.\n- AUC = 1.0: perfect\n- AUC = 0.5: random guessing\n- AUC > 0.8: good model`;
        code = `from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import roc_auc_score, roc_curve\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(300, 3)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nmodel = LogisticRegression().fit(X_train, y_train)\nprobs = model.predict_proba(X_test)[:, 1]\n\nauc = roc_auc_score(y_test, probs)\nfpr, tpr, thresholds = roc_curve(y_test, probs)\n\nprint(f"AUC Score: {auc:.4f}")\nprint(f"\\nThreshold → TPR, FPR:")\nfor t, tp, fp in zip(thresholds[::10], tpr[::10], fpr[::10]):\n    print(f"  {t:.2f} → TPR={tp:.2f}, FPR={fp:.2f}")`;
        questions = ["What does the ROC curve show?", "What is a good AUC score?", "AUC=0.5 means what?", "ROC vs Precision-Recall curve?"];
    }
    else if (t.includes('cross-validation') || t.includes('k-fold')) {
        theory = `**Cross-Validation:** Split data into K folds, use each fold as test once.\n- More reliable than single train/test split\n- K=5 or K=10 is standard\n- Reports mean ± std of scores\n\n**StratifiedKFold:** Maintains class balance in each fold.`;
        code = `from sklearn.model_selection import cross_val_score, StratifiedKFold\nfrom sklearn.ensemble import RandomForestClassifier\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 5)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\n\nmodel = RandomForestClassifier(n_estimators=50, random_state=42)\n\n# 5-fold cross-validation\nscores = cross_val_score(model, X, y, cv=5, scoring='accuracy')\nprint(f"5-Fold CV Accuracy: {scores.mean():.3f} ± {scores.std():.3f}")\nprint(f"Individual folds: {scores.round(3)}")\n\n# Stratified K-Fold\nskf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\nscores = cross_val_score(model, X, y, cv=skf, scoring='f1')\nprint(f"\\nStratified 5-Fold F1: {scores.mean():.3f} ± {scores.std():.3f}")`;
        questions = ["What is K-fold cross-validation?", "Why is CV better than single split?", "What is StratifiedKFold?", "How to interpret mean ± std?"];
    }
    else if (t.includes('bias-variance')) {
        theory = `**Bias:** Error from wrong assumptions → underfitting\n**Variance:** Error from sensitivity to training data → overfitting\n\n**Tradeoff:** Can't minimize both simultaneously.\n- High bias: model too simple\n- High variance: model too complex\n- Goal: sweet spot in between`;
        code = `from sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(300, 5)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\nprint("Depth | Train Acc | Test Acc  | Gap (overfit?)")\nprint("-" * 50)\nfor depth in [1, 3, 5, 10, None]:\n    model = DecisionTreeClassifier(max_depth=depth, random_state=42)\n    model.fit(X_train, y_train)\n    train_acc = model.score(X_train, y_train)\n    test_acc = model.score(X_test, y_test)\n    gap = train_acc - test_acc\n    label = "⚠️ overfit" if gap > 0.1 else "✅"\n    d = str(depth) if depth else "None"\n    print(f"  {d:5s} | {train_acc:.3f}     | {test_acc:.3f}     | {gap:.3f} {label}")`;
        questions = ["What is bias vs variance?", "How to detect underfitting?", "How to detect overfitting?", "3 ways to reduce variance."];
    }
    else if (t.includes('decision tree') && (t.includes('gini') || t.includes('entropy'))) {
        theory = `**Decision Tree:** Makes decisions by splitting data on features.\n- **Gini Impurity:** Measures how often randomly chosen element is misclassified\n- **Entropy:** Measures disorder/uncertainty (information theory)\n- Splits on feature that gives best information gain`;
        code = `from sklearn.tree import DecisionTreeClassifier, export_text\nfrom sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\n\ndata = load_iris()\nX_train, X_test, y_train, y_test = train_test_split(\n    data.data, data.target, test_size=0.2, random_state=42)\n\n# Gini criterion\ntree_gini = DecisionTreeClassifier(max_depth=3, criterion='gini', random_state=42)\ntree_gini.fit(X_train, y_train)\nprint(f"Gini accuracy: {tree_gini.score(X_test, y_test):.2%}")\n\n# Entropy criterion\ntree_ent = DecisionTreeClassifier(max_depth=3, criterion='entropy', random_state=42)\ntree_ent.fit(X_train, y_train)\nprint(f"Entropy accuracy: {tree_ent.score(X_test, y_test):.2%}")\n\n# Visualize tree rules\nprint(f"\\nTree rules:\\n{export_text(tree_gini, feature_names=data.feature_names)}")`;
        questions = ["How does a decision tree split?", "Gini vs Entropy?", "What is information gain?", "Why prune decision trees?"];
    }
    else if (t.includes('random forest') || t.includes('bagging')) {
        theory = `**Random Forest:** Ensemble of decision trees using bagging.\n- Each tree trained on random subset of data AND features\n- Final prediction = majority vote (classification) or average (regression)\n- Reduces overfitting vs single tree`;
        code = `from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(300, 10)\ny = (X[:, 0] + X[:, 1] - X[:, 2] > 0).astype(int)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\n# Compare number of trees\nfor n in [1, 10, 50, 100, 200]:\n    model = RandomForestClassifier(n_estimators=n, random_state=42)\n    model.fit(X_train, y_train)\n    acc = accuracy_score(y_test, model.predict(X_test))\n    print(f"Trees={n:3d}: Accuracy={acc:.3f}")\n\n# Feature importance\nmodel = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_train, y_train)\nfor i, imp in enumerate(model.feature_importances_):\n    bar = "█" * int(imp * 50)\n    print(f"  Feature {i}: {imp:.3f} {bar}")`;
        questions = ["How does Random Forest work?", "What is bagging?", "Why does RF reduce overfitting?", "How to read feature importance?"];
    }
    else if (t.includes('xgboost')) {
        theory = `**XGBoost:** Extreme Gradient Boosting — the #1 algorithm for tabular data.\n- Builds trees sequentially, each fixing errors of previous\n- L1/L2 regularization built-in\n- Handles missing values automatically\n- Won most Kaggle competitions 2015-2020`;
        code = `from sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\ntry:\n    from xgboost import XGBClassifier\nexcept ImportError:\n    print("Install: pip install xgboost")\n    exit()\n\nnp.random.seed(42)\nX = np.random.randn(500, 10)\ny = (X[:, 0] + X[:, 1]*2 - X[:, 2] > 0.5).astype(int)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\nmodel = XGBClassifier(\n    n_estimators=100, max_depth=4, learning_rate=0.1,\n    eval_metric='logloss', random_state=42\n)\nmodel.fit(X_train, y_train)\nprint(f"XGBoost accuracy: {accuracy_score(y_test, model.predict(X_test)):.2%}")\n\n# Feature importance\nfor i, imp in enumerate(model.feature_importances_[:5]):\n    print(f"  Feature {i}: {imp:.3f}")`;
        questions = ["How is XGBoost different from Random Forest?", "What is gradient boosting?", "Key hyperparameters to tune?", "Why is XGBoost popular for tabular data?"];
    }
    else if (t.includes('gridsearch') || t.includes('randomizedsearch') || t.includes('hyperparameter')) {
        theory = `**Hyperparameter Tuning:** Finding optimal model settings.\n- **GridSearchCV:** Try ALL combinations (exhaustive but slow)\n- **RandomizedSearchCV:** Try N random combos (faster, often equally good)\n- Both use cross-validation internally`;
        code = `from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 5)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\n# GridSearchCV\nparam_grid = {'n_estimators': [50, 100], 'max_depth': [3, 5, 10]}\ngrid = GridSearchCV(RandomForestClassifier(random_state=42),\n                    param_grid, cv=3, scoring='accuracy')\ngrid.fit(X_train, y_train)\n\nprint(f"Best params: {grid.best_params_}")\nprint(f"Best CV score: {grid.best_score_:.3f}")\nprint(f"Test score: {grid.score(X_test, y_test):.3f}")`;
        questions = ["Grid vs Randomized search?", "What is a hyperparameter vs parameter?", "How does GridSearchCV use CV?", "When to use RandomizedSearchCV?"];
    }
    else if (t.includes('pipeline') && t.includes('sklearn')) {
        theory = `**sklearn Pipeline:** Chain preprocessing + model into one object.\n- Prevents data leakage (fit_transform on train, transform on test)\n- Clean, production-ready code\n- Works with GridSearchCV`;
        code = `from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split, cross_val_score\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 5)\ny = (X[:, 0] + X[:, 1] > 0).astype(int)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\n# Pipeline: Scale → Model\npipe = Pipeline([\n    ('scaler', StandardScaler()),\n    ('model', RandomForestClassifier(n_estimators=100, random_state=42))\n])\n\npipe.fit(X_train, y_train)\nprint(f"Test accuracy: {pipe.score(X_test, y_test):.3f}")\n\n# CV with pipeline (prevents leakage!)\nscores = cross_val_score(pipe, X, y, cv=5)\nprint(f"5-fold CV: {scores.mean():.3f} ± {scores.std():.3f}")`;
        questions = ["Why use sklearn Pipeline?", "How does Pipeline prevent data leakage?", "How to use Pipeline with GridSearchCV?", "What steps go in a typical pipeline?"];
    }
    else if (t.includes('feature engineering') && t.includes('creating')) {
        theory = `**Feature Engineering:** Creating new features from raw data.\n- Domain knowledge is key\n- Example: From date → day_of_week, is_weekend, month\n- Interactions: feature1 × feature2\n- Aggregations: mean purchase per user`;
        code = `import numpy as np\nimport pandas as pd\n\ndf = pd.DataFrame({\n    'price': [100, 250, 80, 500, 150],\n    'quantity': [2, 1, 5, 1, 3],\n    'date': pd.to_datetime(['2026-01-15','2026-02-20','2026-03-05','2026-01-30','2026-02-14'])\n})\n\n# Create features\ndf['total_amount'] = df['price'] * df['quantity']\ndf['month'] = df['date'].dt.month\ndf['day_of_week'] = df['date'].dt.dayofweek\ndf['is_weekend'] = df['day_of_week'].isin([5,6]).astype(int)\ndf['price_log'] = np.log1p(df['price'])\ndf['price_bin'] = pd.cut(df['price'], bins=[0,100,300,1000], labels=['low','mid','high'])\n\nprint(df.to_string())`;
        questions = ["What is feature engineering?", "Give 5 features from a date column.", "What are interaction features?", "When to use log transformation?"];
    }
    else if (t.includes('imbalanced') || t.includes('smote')) {
        theory = `**Imbalanced Data:** When one class has much fewer samples (e.g., fraud: 1% vs 99%).\n\n**Solutions:**\n- **SMOTE:** Create synthetic samples of minority class\n- **class_weight='balanced':** Penalize errors on minority more\n- **Undersample** majority class\n- Use F1/AUC instead of accuracy!`;
        code = `from sklearn.datasets import make_classification\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import f1_score\nimport numpy as np\n\n# Create imbalanced dataset (95% vs 5%)\nX, y = make_classification(n_samples=1000, weights=[0.95, 0.05], random_state=42)\nprint(f"Class distribution: {np.bincount(y)}")\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n\n# Without handling\nmodel1 = RandomForestClassifier(random_state=42).fit(X_train, y_train)\nf1_1 = f1_score(y_test, model1.predict(X_test))\n\n# With class_weight='balanced'\nmodel2 = RandomForestClassifier(class_weight='balanced', random_state=42).fit(X_train, y_train)\nf1_2 = f1_score(y_test, model2.predict(X_test))\n\nprint(f"Without balancing: F1={f1_1:.3f}")\nprint(f"With class_weight:  F1={f1_2:.3f}")`;
        questions = ["Why is accuracy bad for imbalanced data?", "How does SMOTE work?", "What does class_weight='balanced' do?", "3 strategies for imbalanced datasets."];
    }
    else if (t.includes('k-means') || t.includes('clustering')) {
        theory = `**K-Means Clustering:** Unsupervised — groups data into K clusters.\n1. Initialize K centroids randomly\n2. Assign each point to nearest centroid\n3. Update centroids to cluster means\n4. Repeat until convergence\n\n**Elbow Method:** Plot inertia vs K, choose the "elbow" point.`;
        code = `from sklearn.cluster import KMeans\nimport numpy as np\n\nnp.random.seed(42)\nX = np.vstack([\n    np.random.randn(50, 2) + [2, 2],\n    np.random.randn(50, 2) + [-2, -2],\n    np.random.randn(50, 2) + [2, -2]\n])\n\nmodel = KMeans(n_clusters=3, random_state=42, n_init=10)\nlabels = model.fit_predict(X)\n\nprint(f"Cluster centers:\\n{model.cluster_centers_.round(2)}")\nprint(f"Cluster sizes: {np.bincount(labels)}")\n\n# Elbow method\nprint("\\nElbow method:")\nfor k in range(2, 8):\n    km = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X)\n    print(f"  K={k}: inertia={km.inertia_:.1f}")`;
        questions = ["How does K-Means work?", "What is the elbow method?", "How to choose K?", "K-Means limitations?"];
    }
    else if (t.includes('pca') || t.includes('dimensionality')) {
        theory = `**PCA:** Reduces dimensions while keeping maximum variance.\n- Projects data onto principal components (directions of max variance)\n- Use when: too many features, visualization, reducing noise\n- Explain variance ratio tells you how much info each component captures`;
        code = `from sklearn.decomposition import PCA\nfrom sklearn.preprocessing import StandardScaler\nimport numpy as np\n\nnp.random.seed(42)\nX = np.random.randn(200, 10)  # 10 features\n\n# Scale first (required!)\nX_scaled = StandardScaler().fit_transform(X)\n\n# PCA to 3 components\npca = PCA(n_components=3)\nX_pca = pca.fit_transform(X_scaled)\n\nprint(f"Original shape: {X.shape}")\nprint(f"Reduced shape: {X_pca.shape}")\nprint(f"Variance explained: {pca.explained_variance_ratio_.round(3)}")\nprint(f"Total variance: {sum(pca.explained_variance_ratio_):.1%}")\n\n# How many components for 95% variance?\npca_full = PCA().fit(X_scaled)\ncumvar = np.cumsum(pca_full.explained_variance_ratio_)\nn95 = np.argmax(cumvar >= 0.95) + 1\nprint(f"\\nComponents for 95% variance: {n95}")`;
        questions = ["What does PCA do?", "Why scale before PCA?", "How many components to keep?", "When to use PCA?"];
    }
    else if (t.includes('saving') || t.includes('joblib') || t.includes('pickle')) {
        theory = `**Model Saving:** Save trained models to reuse without retraining.\n- **Joblib:** Recommended for sklearn models (handles numpy arrays efficiently)\n- **Pickle:** Python standard library\n\n**Save everything:** Model + scaler + encoder — all components of the pipeline!`;
        code = `from sklearn.ensemble import RandomForestClassifier\nimport joblib\nimport numpy as np\n\n# Train model\nnp.random.seed(42)\nX = np.random.randn(100, 3)\ny = (X[:, 0] > 0).astype(int)\nmodel = RandomForestClassifier(random_state=42).fit(X, y)\n\n# Save\njoblib.dump(model, 'model.pkl')\nprint("✅ Model saved as model.pkl")\n\n# Load\nloaded_model = joblib.load('model.pkl')\npred = loaded_model.predict(X[:3])\nprint(f"Loaded model predictions: {pred}")\nprint(f"Same as original: {np.array_equal(pred, model.predict(X[:3]))}")\n\nimport os\nprint(f"File size: {os.path.getsize('model.pkl') / 1024:.1f} KB")`;
        questions = ["How to save sklearn models?", "Joblib vs Pickle?", "Why save the scaler too?", "How to version saved models?"];
    }

    if (!theory) return null;
    return { content: `### Day ${day}: ${topic}\n\n${theory}`, code: `# Day ${day}: ${topic}\n${code}`, questions };
};
