// Phase 2: Data Handling & SQL (Days 41-80) specific content
module.exports = function (day, topic, t) {
    let theory, code, questions;

    if (t.includes('creating 1d') || t.includes('creating') && t.includes('array')) {
        theory = `**NumPy arrays** are faster and use less memory than Python lists. They support vectorized operations.\n\n**Creating arrays:**\n- \`np.array([1,2,3])\` — from list\n- \`np.zeros(5)\`, \`np.ones(5)\` — filled arrays\n- \`np.arange(0,10,2)\` — like range()\n- \`np.linspace(0,1,5)\` — evenly spaced`;
        code = `import numpy as np\n\n# From list\narr = np.array([1, 2, 3, 4, 5])\nprint(f"1D: {arr}, dtype: {arr.dtype}")\n\n# 2D array\nmatrix = np.array([[1,2,3],[4,5,6]])\nprint(f"2D shape: {matrix.shape}")\n\n# Special arrays\nprint(f"Zeros: {np.zeros(5)}")\nprint(f"Ones: {np.ones((2,3))}")\nprint(f"Range: {np.arange(0, 10, 2)}")\nprint(f"Linspace: {np.linspace(0, 1, 5)}")\nprint(f"Identity:\\n{np.eye(3)}")`;
        questions = ["How is a NumPy array different from a Python list?", "Create a 3x3 matrix of zeros.", "What is np.linspace and when to use it?", "What is dtype in NumPy?"];
    }
    else if (t.includes('indexing') && t.includes('numpy') || t.includes('fancy indexing')) {
        theory = `**NumPy Indexing:**\n- Basic: \`arr[0]\`, \`arr[-1]\`\n- Slicing: \`arr[1:4]\`, \`arr[::-1]\`\n- 2D: \`matrix[row, col]\`\n- Boolean: \`arr[arr > 5]\`\n- Fancy: \`arr[[0, 2, 4]]\` — index with array`;
        code = `import numpy as np\n\narr = np.array([10, 20, 30, 40, 50, 60])\n\n# Basic indexing\nprint(f"First: {arr[0]}, Last: {arr[-1]}")\nprint(f"Slice: {arr[1:4]}")\n\n# 2D indexing\nm = np.array([[1,2,3],[4,5,6],[7,8,9]])\nprint(f"Row 1: {m[1]}")\nprint(f"Element [1,2]: {m[1,2]}")\nprint(f"Column 0: {m[:,0]}")\n\n# Boolean indexing (filtering)\ndata = np.array([15, 22, 8, 45, 30, 12])\nprint(f"Above 20: {data[data > 20]}")\n\n# Fancy indexing\nprint(f"Select [0,2,4]: {arr[[0,2,4]]}")`;
        questions = ["How does boolean indexing work?", "Get all elements > 50 from array.", "Difference between slicing and fancy indexing?", "How to select a column from 2D array?"];
    }
    else if (t.includes('mathematical') || t.includes('statistical') && t.includes('numpy')) {
        theory = `**NumPy Math:** Element-wise operations without loops.\n- Arithmetic: \`arr + 1\`, \`arr * 2\`, \`arr ** 2\`\n- Stats: \`np.mean()\`, \`np.std()\`, \`np.median()\`\n- Aggregation: \`np.sum()\`, \`np.min()\`, \`np.max()\`\n- Axis: \`axis=0\` (columns), \`axis=1\` (rows)`;
        code = `import numpy as np\n\narr = np.array([10, 20, 30, 40, 50])\n\n# Vectorized arithmetic\nprint(f"arr * 2: {arr * 2}")\nprint(f"arr ** 2: {arr ** 2}")\n\n# Statistics\nprint(f"Mean: {np.mean(arr)}")\nprint(f"Std: {np.std(arr):.2f}")\nprint(f"Median: {np.median(arr)}")\n\n# 2D axis operations\nmatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])\nprint(f"Sum all: {matrix.sum()}")\nprint(f"Sum cols: {matrix.sum(axis=0)}")\nprint(f"Sum rows: {matrix.sum(axis=1)}")\nprint(f"Max each row: {matrix.max(axis=1)}")`;
        questions = ["What are vectorized operations?", "Difference between axis=0 and axis=1?", "Calculate mean and std of an array.", "Why is NumPy faster than Python loops?"];
    }
    else if (t.includes('reshaping') || t.includes('broadcasting') || t.includes('vectorization')) {
        theory = `**Reshaping:** Change array dimensions without changing data.\n- \`arr.reshape(2,3)\` — new shape\n- \`arr.flatten()\` — to 1D\n- \`arr.T\` — transpose\n\n**Broadcasting:** NumPy automatically expands smaller arrays to match larger ones for operations.\n\n**Vectorization:** Replace Python loops with NumPy operations for 100x speedup.`;
        code = `import numpy as np\n\n# Reshape\narr = np.arange(12)\nprint(f"Original: {arr}")\nprint(f"Reshaped 3x4:\\n{arr.reshape(3,4)}")\nprint(f"Reshaped 2x6:\\n{arr.reshape(2,6)}")\n\n# Broadcasting\na = np.array([[1],[2],[3]])  # 3x1\nb = np.array([10, 20, 30])   # 1x3\nprint(f"\\nBroadcast:\\n{a + b}")  # 3x3 result\n\n# Vectorization speed\nimport time\nn = 1000000\npy_list = list(range(n))\nnp_arr = np.arange(n)\n\nstart = time.time()\nresult1 = [x*2 for x in py_list]\nt1 = time.time() - start\n\nstart = time.time()\nresult2 = np_arr * 2\nt2 = time.time() - start\n\nprint(f"\\nPython loop: {t1:.4f}s")\nprint(f"NumPy vector: {t2:.4f}s")\nprint(f"NumPy is {t1/t2:.0f}x faster!")`;
        questions = ["What is broadcasting?", "How does reshape work?", "Why is vectorization faster than loops?", "Reshape a 1D array of 12 elements into 3x4 matrix."];
    }
    else if (t.includes('random') && t.includes('numpy') || t.includes('synthetic')) {
        theory = `**np.random** generates random data for testing and simulation.\n- \`np.random.rand(n)\` — uniform [0,1)\n- \`np.random.randn(n)\` — normal distribution\n- \`np.random.randint(low,high,size)\`\n- \`np.random.choice(arr,size)\`\n- \`np.random.seed(42)\` — reproducibility`;
        code = `import numpy as np\nnp.random.seed(42)  # Reproducible\n\n# Random arrays\nprint(f"Uniform: {np.random.rand(5).round(2)}")\nprint(f"Normal: {np.random.randn(5).round(2)}")\nprint(f"Integers: {np.random.randint(1, 100, 5)}")\n\n# Synthetic dataset\nn = 100\nages = np.random.normal(35, 10, n).astype(int)\nsalaries = ages * 1500 + np.random.normal(0, 5000, n)\nprint(f"\\nAges: mean={ages.mean():.0f}, std={ages.std():.0f}")\nprint(f"Salaries: mean={salaries.mean():.0f}")\n\n# Random choice\ncategories = np.random.choice(['A','B','C'], 10, p=[0.5,0.3,0.2])\nprint(f"\\nCategories: {categories}")\n\n# Shuffle\narr = np.arange(10)\nnp.random.shuffle(arr)\nprint(f"Shuffled: {arr}")`;
        questions = ["Why use np.random.seed(42)?", "Generate 100 samples from normal distribution.", "How to create synthetic dataset?", "Difference between rand and randn?"];
    }
    else if (t.includes('install') && t.includes('sql') || t.includes('first queries')) {
        theory = `**SQL (Structured Query Language)** is the standard language for relational databases.\n\n**Setup Options:**\n- PostgreSQL — production standard\n- MySQL — widely used\n- SQLite — lightweight, no server needed\n\n**First Queries:** \`SELECT * FROM table;\``;
        code = `# SQL Setup and First Queries\n# Practice in any SQL client or use Python:\nimport sqlite3\n\nconn = sqlite3.connect(':memory:')\ncursor = conn.cursor()\n\n# Create table\ncursor.execute('''\n    CREATE TABLE employees (\n        id INTEGER PRIMARY KEY,\n        name TEXT NOT NULL,\n        role TEXT,\n        salary REAL\n    )\n''')\n\n# Insert data\nemployees = [\n    (1, 'Alice', 'ML Engineer', 120000),\n    (2, 'Bob', 'Data Analyst', 80000),\n    (3, 'Carol', 'Backend Dev', 95000),\n    (4, 'Dave', 'ML Engineer', 110000),\n]\ncursor.executemany('INSERT INTO employees VALUES (?,?,?,?)', employees)\n\n# First queries\nprint("All employees:")\nfor row in cursor.execute('SELECT * FROM employees'):\n    print(f"  {row}")\n\nprint("\\nML Engineers:")\nfor row in cursor.execute("SELECT name, salary FROM employees WHERE role='ML Engineer'"):\n    print(f"  {row[0]}: {row[1]}")\n\nconn.close()`;
        questions = ["What is SQL used for?", "Difference between PostgreSQL and SQLite?", "Write SELECT to get all rows from a table.", "How to filter rows with WHERE?"];
    }
    else if (t.includes('create table') || t.includes('data types') && t.includes('sql')) {
        theory = `**CREATE TABLE** defines the structure of your data.\n\n**Common Data Types:**\n- INTEGER, REAL/FLOAT, TEXT/VARCHAR\n- DATE, TIMESTAMP, BOOLEAN\n\n**Constraints:** PRIMARY KEY, NOT NULL, UNIQUE, DEFAULT, FOREIGN KEY`;
        code = `# SQL: CREATE TABLE\nsql = \"\"\"\n-- Users table\nCREATE TABLE users (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    email VARCHAR(255) UNIQUE NOT NULL,\n    age INTEGER CHECK (age >= 0),\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- Orders table with foreign key\nCREATE TABLE orders (\n    id SERIAL PRIMARY KEY,\n    user_id INTEGER REFERENCES users(id),\n    amount DECIMAL(10,2) NOT NULL,\n    status VARCHAR(20) DEFAULT 'pending',\n    order_date DATE NOT NULL\n);\n\"\"\"\nprint(sql)`;
        questions = ["What is a PRIMARY KEY?", "Difference between VARCHAR and TEXT?", "What is a FOREIGN KEY?", "What constraints can you add to columns?"];
    }
    else if (t.includes('insert') || t.includes('update') || t.includes('delete') || t.includes('crud')) {
        theory = `**CRUD Operations:**\n- **C**reate: \`INSERT INTO table (cols) VALUES (vals)\`\n- **R**ead: \`SELECT cols FROM table\`\n- **U**pdate: \`UPDATE table SET col=val WHERE condition\`\n- **D**elete: \`DELETE FROM table WHERE condition\`\n\n⚠️ Always use WHERE with UPDATE/DELETE to avoid affecting all rows!`;
        code = `# SQL: CRUD Operations\nsql = \"\"\"\n-- INSERT\nINSERT INTO users (name, email, age)\nVALUES ('Ruban', 'ruban@example.com', 25);\n\n-- INSERT multiple\nINSERT INTO users (name, email, age) VALUES\n('Alice', 'alice@co.com', 28),\n('Bob', 'bob@co.com', 32);\n\n-- UPDATE (always use WHERE!)\nUPDATE users SET age = 26 WHERE name = 'Ruban';\n\n-- DELETE (always use WHERE!)\nDELETE FROM users WHERE email = 'bob@co.com';\n\n-- Verify changes\nSELECT * FROM users;\n\"\"\"\nprint(sql)`;
        questions = ["What are CRUD operations?", "Why always use WHERE with UPDATE/DELETE?", "How to insert multiple rows at once?", "What happens if you run DELETE without WHERE?"];
    }
    else if (t.includes('select') && t.includes('where') || t.includes('distinct') || t.includes('aliases')) {
        theory = `**SELECT** retrieves data. **WHERE** filters rows.\n\n**Key Clauses:**\n- \`DISTINCT\` — unique values only\n- \`AS\` — column aliases for readability\n- \`ORDER BY\` — sort results\n- \`LIMIT\` — restrict row count`;
        code = `# SQL: SELECT, WHERE, DISTINCT, ALIASES\nsql = \"\"\"\n-- Basic SELECT\nSELECT name, salary FROM employees;\n\n-- WHERE filters\nSELECT * FROM employees WHERE salary > 90000;\nSELECT * FROM employees WHERE role = 'ML Engineer' AND salary > 100000;\n\n-- DISTINCT\nSELECT DISTINCT role FROM employees;\n\n-- Aliases\nSELECT \n    name AS employee_name,\n    salary AS annual_salary,\n    salary / 12 AS monthly_salary\nFROM employees;\n\n-- ORDER BY + LIMIT\nSELECT name, salary FROM employees\nORDER BY salary DESC\nLIMIT 3;\n\"\"\"\nprint(sql)`;
        questions = ["What does DISTINCT do?", "How to sort results descending?", "What are column aliases used for?", "Filter employees earning > 50000 in 'Engineering'."];
    }
    else if (t.includes(' in,') || t.includes('between') || t.includes('like') || t.includes('pattern')) {
        theory = `**IN** — match any value in a list: \`WHERE city IN ('Delhi','Mumbai')\`\n\n**BETWEEN** — range filter: \`WHERE salary BETWEEN 50000 AND 100000\`\n\n**LIKE** — pattern matching:\n- \`%\` matches any characters: \`'%kumar'\`\n- \`_\` matches one character: \`'_an'\``;
        code = `# SQL: IN, BETWEEN, LIKE\nsql = \"\"\"\n-- IN: match from a list\nSELECT * FROM employees\nWHERE role IN ('ML Engineer', 'Data Analyst', 'Backend Dev');\n\n-- BETWEEN: range filter\nSELECT name, salary FROM employees\nWHERE salary BETWEEN 80000 AND 120000;\n\n-- LIKE: pattern matching\nSELECT * FROM employees WHERE name LIKE 'A%';     -- starts with A\nSELECT * FROM employees WHERE email LIKE '%@gmail.com';  -- Gmail\nSELECT * FROM employees WHERE name LIKE '_o%';     -- 2nd char is 'o'\n\n-- NOT IN / NOT LIKE\nSELECT * FROM employees\nWHERE role NOT IN ('Intern', 'Contractor');\n\"\"\"\nprint(sql)`;
        questions = ["When to use IN vs multiple OR conditions?", "What is the difference between LIKE '%a' and LIKE 'a%'?", "How does BETWEEN work with dates?", "Write query: find employees with names starting with 'S'."];
    }
    else if (t.includes('inner join')) {
        theory = `**INNER JOIN** returns only rows that have matches in BOTH tables.\n\n**Syntax:**\n\`\`\`sql\nSELECT * FROM orders\nINNER JOIN customers ON orders.customer_id = customers.id;\n\`\`\`\n\n**Key:** If no match exists, the row is excluded from results.`;
        code = `# SQL: INNER JOIN\nsql = \"\"\"\n-- Join orders with customers\nSELECT \n    o.id AS order_id,\n    c.name AS customer_name,\n    o.amount,\n    o.order_date\nFROM orders o\nINNER JOIN customers c ON o.customer_id = c.id;\n\n-- Join with filtering\nSELECT \n    c.name,\n    COUNT(o.id) AS total_orders,\n    SUM(o.amount) AS total_spent\nFROM customers c\nINNER JOIN orders o ON c.id = o.customer_id\nGROUP BY c.name\nHAVING total_spent > 1000\nORDER BY total_spent DESC;\n\"\"\"\nprint(sql)`;
        questions = ["What does INNER JOIN return?", "What happens to unmatched rows?", "Write a JOIN between orders and products.", "When to use table aliases?"];
    }
    else if (t.includes('left join') || t.includes('right join') || t.includes('full outer')) {
        theory = `**LEFT JOIN** — all rows from left table + matches from right (NULL if no match)\n**RIGHT JOIN** — all rows from right table + matches from left\n**FULL OUTER** — all rows from both tables\n\n**Use Case:** LEFT JOIN is most common — "show all customers, even those with no orders."`;
        code = `# SQL: LEFT, RIGHT, FULL OUTER JOIN\nsql = \"\"\"\n-- LEFT JOIN: all customers, even without orders\nSELECT \n    c.name,\n    COALESCE(SUM(o.amount), 0) AS total_spent\nFROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id\nGROUP BY c.name;\n\n-- Find customers with NO orders\nSELECT c.name\nFROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id\nWHERE o.id IS NULL;\n\n-- FULL OUTER JOIN (PostgreSQL)\nSELECT *\nFROM table_a a\nFULL OUTER JOIN table_b b ON a.id = b.id;\n\"\"\"\nprint(sql)`;
        questions = ["Difference between LEFT and INNER JOIN?", "How to find rows with no match using LEFT JOIN?", "When to use FULL OUTER JOIN?", "What does COALESCE do?"];
    }
    else if (t.includes('self-join') || t.includes('cross-join') || t.includes('multi-table')) {
        theory = `**Self-Join** — join a table with itself (e.g., find employees and their managers).\n**Cross-Join** — every row combined with every other row (cartesian product).\n**Multi-Table** — join 3+ tables in one query.`;
        code = `# SQL: Self-Join, Cross-Join, Multi-Table\nsql = \"\"\"\n-- Self-Join: employee and their manager\nSELECT \n    e.name AS employee,\n    m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;\n\n-- Cross-Join: all combinations\nSELECT color, size\nFROM colors CROSS JOIN sizes;\n\n-- Multi-Table Join\nSELECT \n    o.id AS order_id,\n    c.name AS customer,\n    p.name AS product,\n    oi.quantity\nFROM orders o\nJOIN customers c ON o.customer_id = c.id\nJOIN order_items oi ON o.id = oi.order_id\nJOIN products p ON oi.product_id = p.id;\n\"\"\"\nprint(sql)`;
        questions = ["What is a self-join? Give example.", "When would you use cross-join?", "How to join 3 tables?", "Write self-join to find employee-manager pairs."];
    }
    else if (t.includes('count') || t.includes('sum') || t.includes('avg') || t.includes('aggregate')) {
        theory = `**Aggregate Functions** compute a single value from multiple rows:\n- \`COUNT(*)\` — number of rows\n- \`SUM(col)\` — total\n- \`AVG(col)\` — average\n- \`MIN(col)\`, \`MAX(col)\`\n\n**NULL handling:** Aggregates ignore NULLs (except COUNT(*)).`;
        code = `# SQL: Aggregate Functions\nsql = \"\"\"\n-- Basic aggregates\nSELECT \n    COUNT(*) AS total_employees,\n    AVG(salary) AS avg_salary,\n    MIN(salary) AS min_salary,\n    MAX(salary) AS max_salary,\n    SUM(salary) AS total_payroll\nFROM employees;\n\n-- Count by role\nSELECT \n    role,\n    COUNT(*) AS headcount,\n    ROUND(AVG(salary), 2) AS avg_salary\nFROM employees\nGROUP BY role\nORDER BY avg_salary DESC;\n\"\"\"\nprint(sql)`;
        questions = ["What are aggregate functions?", "Does COUNT(*) include NULLs?", "Calculate average salary by department.", "Difference between COUNT(*) and COUNT(column)?"];
    }
    else if (t.includes('group by') || t.includes('having')) {
        theory = `**GROUP BY** groups rows that share values, used with aggregates.\n\n**HAVING** filters groups (like WHERE but for aggregates).\n\n**Order:** SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY → LIMIT`;
        code = `# SQL: GROUP BY and HAVING\nsql = \"\"\"\n-- Revenue by category\nSELECT \n    category,\n    COUNT(*) AS num_products,\n    SUM(price) AS total_revenue,\n    AVG(price) AS avg_price\nFROM products\nGROUP BY category\nORDER BY total_revenue DESC;\n\n-- HAVING: filter groups\nSELECT \n    customer_id,\n    COUNT(*) AS order_count,\n    SUM(amount) AS total_spent\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) >= 5 AND SUM(amount) > 10000\nORDER BY total_spent DESC;\n\"\"\"\nprint(sql)`;
        questions = ["Difference between WHERE and HAVING?", "What is GROUP BY used for?", "Find categories with more than 10 products.", "What is the SQL execution order?"];
    }
    else if (t.includes('subquer')) {
        theory = `**Subqueries** are queries inside queries.\n\n**Types:**\n- **Scalar:** returns single value: \`WHERE salary > (SELECT AVG(salary)...)\`\n- **Row:** returns one row\n- **Table:** returns multiple rows, used with IN or EXISTS`;
        code = `# SQL: Subqueries\nsql = \"\"\"\n-- Scalar: above-average salary\nSELECT name, salary FROM employees\nWHERE salary > (SELECT AVG(salary) FROM employees);\n\n-- IN subquery\nSELECT name FROM employees\nWHERE department_id IN (\n    SELECT id FROM departments WHERE location = 'Bangalore'\n);\n\n-- EXISTS\nSELECT c.name FROM customers c\nWHERE EXISTS (\n    SELECT 1 FROM orders o\n    WHERE o.customer_id = c.id AND o.amount > 5000\n);\n\n-- Subquery as table (derived table)\nSELECT dept, avg_salary FROM (\n    SELECT department AS dept, AVG(salary) AS avg_salary\n    FROM employees GROUP BY department\n) sub\nWHERE avg_salary > 80000;\n\"\"\"\nprint(sql)`;
        questions = ["What is a subquery?", "3 types of subqueries?", "Find employees earning above average salary.", "When to use EXISTS vs IN?"];
    }
    else if (t.includes('window') && t.includes('row_number') || t.includes('rank') || t.includes('dense_rank')) {
        theory = `**Window Functions** perform calculations across rows without collapsing them (unlike GROUP BY).\n\n- \`ROW_NUMBER()\` — unique sequential number\n- \`RANK()\` — same rank for ties, gaps after\n- \`DENSE_RANK()\` — same rank for ties, no gaps`;
        code = `# SQL: Window Functions\nsql = \"\"\"\n-- ROW_NUMBER: rank employees by salary\nSELECT \n    name, role, salary,\n    ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num,\n    RANK() OVER (ORDER BY salary DESC) AS rank,\n    DENSE_RANK() OVER (ORDER BY salary DESC) AS dense_rank\nFROM employees;\n\n-- PARTITION BY: rank within each department\nSELECT \n    name, department, salary,\n    RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dept_rank\nFROM employees;\n\n-- Top earner per department\nSELECT * FROM (\n    SELECT *, ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn\n    FROM employees\n) sub WHERE rn = 1;\n\"\"\"\nprint(sql)`;
        questions = ["Difference between RANK and DENSE_RANK?", "What is PARTITION BY?", "Find top 3 earners per department.", "How do window functions differ from GROUP BY?"];
    }
    else if (t.includes('lead') || t.includes('lag') || t.includes('running total')) {
        theory = `**LAG/LEAD** access previous/next row values:\n- \`LAG(col, 1)\` — previous row's value\n- \`LEAD(col, 1)\` — next row's value\n\n**Running Totals:** \`SUM(col) OVER (ORDER BY date)\``;
        code = `# SQL: LAG, LEAD, Running Totals\nsql = \"\"\"\n-- Monthly revenue with previous month comparison\nSELECT \n    month,\n    revenue,\n    LAG(revenue, 1) OVER (ORDER BY month) AS prev_month,\n    revenue - LAG(revenue, 1) OVER (ORDER BY month) AS growth\nFROM monthly_sales;\n\n-- Running total\nSELECT \n    order_date,\n    amount,\n    SUM(amount) OVER (ORDER BY order_date) AS running_total\nFROM orders;\n\n-- Moving average (3 month)\nSELECT \n    month, revenue,\n    AVG(revenue) OVER (\n        ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW\n    ) AS moving_avg_3m\nFROM monthly_sales;\n\"\"\"\nprint(sql)`;
        questions = ["What does LAG do?", "How to calculate running total?", "What is a moving average in SQL?", "Compare current and previous row values."];
    }
    else if (t.includes('case when') || t.includes('coalesce') || t.includes('null handling')) {
        theory = `**CASE WHEN** — SQL's if-else:\n\`\`\`sql\nCASE WHEN condition THEN result ELSE default END\n\`\`\`\n\n**COALESCE** — returns first non-NULL value\n\n**NULL handling:** IS NULL, IS NOT NULL, IFNULL, NULLIF`;
        code = `# SQL: CASE WHEN, COALESCE, NULL\nsql = \"\"\"\n-- CASE WHEN: categorize salary\nSELECT name, salary,\n    CASE \n        WHEN salary >= 100000 THEN 'Senior'\n        WHEN salary >= 70000 THEN 'Mid'\n        ELSE 'Junior'\n    END AS level\nFROM employees;\n\n-- COALESCE: handle NULLs\nSELECT \n    name,\n    COALESCE(phone, email, 'No contact') AS contact\nFROM customers;\n\n-- NULL filtering\nSELECT * FROM employees WHERE manager_id IS NULL;  -- top managers\nSELECT * FROM employees WHERE manager_id IS NOT NULL;\n\"\"\"\nprint(sql)`;
        questions = ["How does CASE WHEN work?", "What does COALESCE do?", "Difference between NULL and empty string?", "Write CASE to categorize ages into groups."];
    }
    else if (t.includes('sql interview') || t.includes('10 real sql')) {
        theory = `**SQL Interview Tips:**\n1. Always clarify the schema first\n2. Start simple, add complexity\n3. Use CTEs for readability\n4. Think about edge cases (NULLs, duplicates)\n5. Practice writing without an IDE`;
        code = `# SQL Interview Challenges\nsql = \"\"\"\n-- 1. Second highest salary\nSELECT MAX(salary) FROM employees\nWHERE salary < (SELECT MAX(salary) FROM employees);\n\n-- 2. Employees earning more than their manager\nSELECT e.name FROM employees e\nJOIN employees m ON e.manager_id = m.id\nWHERE e.salary > m.salary;\n\n-- 3. Duplicate emails\nSELECT email, COUNT(*) FROM users\nGROUP BY email HAVING COUNT(*) > 1;\n\n-- 4. Customers who never ordered\nSELECT c.name FROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id\nWHERE o.id IS NULL;\n\n-- 5. Running total\nSELECT date, amount,\n    SUM(amount) OVER (ORDER BY date) AS running_total\nFROM sales;\n\"\"\"\nprint(sql)`;
        questions = ["Find second highest salary.", "Find duplicate records.", "Employees earning more than manager.", "Customers with no orders."];
    }
    else if (t.includes('loading csv') || t.includes('loading') && t.includes('pandas')) {
        theory = `**Pandas** reads data from many formats:\n- \`pd.read_csv('file.csv')\`\n- \`pd.read_excel('file.xlsx')\`\n- \`pd.read_json('file.json')\`\n\n**Key Parameters:** sep, header, index_col, na_values, dtype, parse_dates`;
        code = `import pandas as pd\nimport numpy as np\n\n# Create sample CSV\nimport io\ncsv_data = \"\"\"name,age,salary,department\nAlice,28,120000,Engineering\nBob,32,80000,Marketing\nCarol,26,95000,Engineering\nDave,45,110000,Marketing\"\"\"\n\ndf = pd.read_csv(io.StringIO(csv_data))\nprint("DataFrame:")\nprint(df)\nprint(f"\\nShape: {df.shape}")\nprint(f"Columns: {list(df.columns)}")\nprint(f"Dtypes:\\n{df.dtypes}")`;
        questions = ["How to read a CSV file with Pandas?", "What does df.shape return?", "How to specify column types when reading?", "Read CSV with custom separator."];
    }
    else if (t.includes('head') || t.includes('tail') || t.includes('info') || t.includes('describe') || t.includes('audit')) {
        theory = `**Data Audit** — first thing you do with any dataset:\n- \`df.head()\` / \`df.tail()\` — preview rows\n- \`df.info()\` — dtypes, non-null counts\n- \`df.describe()\` — statistics\n- \`df.shape\`, \`df.columns\`, \`df.dtypes\``;
        code = `import pandas as pd\nimport numpy as np\n\n# Sample data\ndf = pd.DataFrame({\n    'name': ['Alice','Bob','Carol','Dave','Eve'],\n    'age': [28, 32, None, 45, 29],\n    'salary': [120000, 80000, 95000, 110000, 87000],\n    'dept': ['Eng','Mkt','Eng','Mkt','Eng']\n})\n\n# Data audit\nprint("=== head() ===")\nprint(df.head(3))\n\nprint("\\n=== info() ===")\ndf.info()\n\nprint("\\n=== describe() ===")\nprint(df.describe())\n\nprint(f"\\nShape: {df.shape}")\nprint(f"Null counts:\\n{df.isnull().sum()}")`;
        questions = ["What is the first thing you do with a new dataset?", "What does df.info() show?", "Difference between describe() and info()?", "How to check for missing values?"];
    }
    else if (t.includes('.loc') || t.includes('.iloc')) {
        theory = `**Selection:**\n- \`.loc[]\` — select by **labels** (row/column names)\n- \`.iloc[]\` — select by **integer position** (0-based index)\n\n**Key difference:** .loc includes the end, .iloc excludes it.`;
        code = `import pandas as pd\n\ndf = pd.DataFrame({\n    'name': ['Alice','Bob','Carol','Dave'],\n    'age': [28, 32, 26, 45],\n    'salary': [120000, 80000, 95000, 110000]\n}, index=['a','b','c','d'])\n\n# .loc — by label\nprint("loc['a']:", df.loc['a'].values)\nprint("loc['a':'c', 'name']:\\n", df.loc['a':'c', 'name'])\n\n# .iloc — by position\nprint("\\niloc[0]:", df.iloc[0].values)\nprint("iloc[0:2, 0:2]:\\n", df.iloc[0:2, 0:2])\n\n# Select specific rows and columns\nprint("\\nNames of first 3:\\n", df.loc['a':'c', ['name','salary']])`;
        questions = ["Difference between .loc and .iloc?", "Select rows 2-4 and columns 'name','salary'.", "Does .loc include the endpoint?", "How to select a single cell?"];
    }
    else if (t.includes('filtering') && t.includes('boolean')) {
        theory = `**Boolean Filtering** — the most common Pandas operation:\n\`\`\`python\ndf[df['salary'] > 100000]           # single condition\ndf[(df['age'] > 25) & (df['dept'] == 'Eng')]  # multiple\n\`\`\`\n\n**Operators:** \`&\` (and), \`|\` (or), \`~\` (not). Always use parentheses!`;
        code = `import pandas as pd\n\ndf = pd.DataFrame({\n    'name': ['Alice','Bob','Carol','Dave','Eve'],\n    'age': [28, 32, 26, 45, 29],\n    'salary': [120000, 80000, 95000, 110000, 87000],\n    'dept': ['Eng','Mkt','Eng','Mkt','Eng']\n})\n\n# Single condition\nhigh_earners = df[df['salary'] > 100000]\nprint("High earners:\\n", high_earners)\n\n# Multiple conditions (use & and parentheses!)\nyoung_eng = df[(df['age'] < 30) & (df['dept'] == 'Eng')]\nprint("\\nYoung engineers:\\n", young_eng)\n\n# isin()\nselected = df[df['dept'].isin(['Eng', 'Data'])]\nprint("\\nEng/Data:\\n", selected)\n\n# String contains\ndf2 = df[df['name'].str.startswith('A')]\nprint("\\nNames starting with A:\\n", df2)`;
        questions = ["How to filter DataFrame rows?", "Why use parentheses with & and |?", "Filter: age > 30 AND salary > 90000.", "How does isin() work?"];
    }

    // Generic fallback for remaining SQL/data topics
    if (!theory) return null;

    return {
        content: `### Day ${day}: ${topic}\n\n${theory}`,
        code: `# Day ${day}: ${topic}\n${code}`,
        questions
    };
};
