// Phase 1 continued: Days 11-25
module.exports = {
    11: {
        content: `### Day 11: While Loops — Break, Continue, and Loop Patterns\n\n**What is a While Loop?**\nA while loop repeats as long as a condition is True. Use it when you don't know in advance how many times to loop.\n\n**Syntax:**\n\`\`\`python\nwhile condition:\n    # do something\n    # update condition to eventually stop\n\`\`\`\n\n**Control Statements:**\n- \`break\` — exit the loop immediately\n- \`continue\` — skip to the next iteration\n- \`else\` — runs if loop completes without break\n\n**Common Patterns:**\n1. **Counter loop:** Initialize counter, loop while counter < limit\n2. **Sentinel loop:** Loop until user enters "quit"\n3. **Validation loop:** Keep asking until valid input received\n\n**Danger: Infinite Loops!**\nAlways ensure the loop condition eventually becomes False. Use \`Ctrl+C\` to stop a runaway loop.`,
        code: `# Day 11: While Loops — Break, Continue, and Patterns\n\n# Basic while loop\ncount = 1\nwhile count <= 5:\n    print(f"Count: {count}")\n    count += 1\n\n# While with break\nprint("\\n=== Guess the Number ===")\nsecret = 7\nattempts = 0\nwhile True:\n    guess = attempts + 5  # simulating guesses: 5, 6, 7\n    attempts += 1\n    if guess == secret:\n        print(f"Correct! Got it in {attempts} attempts")\n        break\n    print(f"Guess {guess}: Wrong!")\n\n# While with continue (skip even numbers)\nprint("\\n=== Odd numbers 1-10 ===")\nn = 0\nwhile n < 10:\n    n += 1\n    if n % 2 == 0:\n        continue  # skip even\n    print(n, end=" ")\nprint()\n\n# Input validation pattern\nprint("\\n=== Sum Calculator ===")\ntotal = 0\nnumbers = [10, 25, -5, 30, 0]  # simulating input\nfor num in numbers:\n    if num == 0:\n        break\n    if num < 0:\n        print(f"Skipping negative: {num}")\n        continue\n    total += num\n    print(f"Added {num}, Total: {total}")\nprint(f"Final total: {total}")\n\n# Countdown\nprint("\\n=== Countdown ===")\ni = 5\nwhile i > 0:\n    print(f"{i}...", end=" ")\n    i -= 1\nprint("Go! 🚀")`,
        questions: ["What is the difference between a for loop and a while loop? When do you use each?", "What does 'break' do inside a loop? How is it different from 'continue'?", "How do you prevent an infinite while loop?", "Write a while loop that keeps dividing a number by 2 until it becomes less than 1."]
    },

    12: {
        content: `### Day 12: Practice Day — 5 Loop and Condition Coding Challenges\n\n**Why Practice Matters:**\nReading code is not the same as writing code. Solving challenges builds muscle memory and problem-solving instincts.\n\n**Today's 5 Challenges:**\n1. **FizzBuzz:** Print 1-50. For multiples of 3 print "Fizz", multiples of 5 print "Buzz", both print "FizzBuzz"\n2. **Sum of Digits:** Given a number like 1234, calculate 1+2+3+4=10\n3. **Reverse a String:** Without using [::-1]\n4. **Find Maximum:** Find the largest number in a list without using max()\n5. **Palindrome Check:** Check if a word reads the same forwards and backwards\n\n**Approach for Each:**\n1. Read the problem carefully\n2. Think of the steps before coding\n3. Write clean code with good variable names\n4. Test with edge cases (empty input, single element, etc.)`,
        code: `# Day 12: 5 Coding Challenges\n\n# Challenge 1: FizzBuzz\nprint("=== Challenge 1: FizzBuzz ===")\nfor i in range(1, 21):\n    if i % 3 == 0 and i % 5 == 0:\n        print("FizzBuzz", end=" ")\n    elif i % 3 == 0:\n        print("Fizz", end=" ")\n    elif i % 5 == 0:\n        print("Buzz", end=" ")\n    else:\n        print(i, end=" ")\nprint()\n\n# Challenge 2: Sum of Digits\nprint("\\n=== Challenge 2: Sum of Digits ===")\ndef sum_of_digits(n):\n    total = 0\n    n = abs(n)  # handle negative\n    while n > 0:\n        total += n % 10\n        n //= 10\n    return total\n\nprint(f"sum_of_digits(1234) = {sum_of_digits(1234)}")  # 10\nprint(f"sum_of_digits(9999) = {sum_of_digits(9999)}")  # 36\n\n# Challenge 3: Reverse a String\nprint("\\n=== Challenge 3: Reverse String ===")\ndef reverse_string(s):\n    result = ""\n    for char in s:\n        result = char + result\n    return result\n\nprint(f"reverse('hello') = {reverse_string('hello')}")\n\n# Challenge 4: Find Maximum\nprint("\\n=== Challenge 4: Find Maximum ===")\ndef find_max(nums):\n    if not nums:\n        return None\n    maximum = nums[0]\n    for n in nums[1:]:\n        if n > maximum:\n            maximum = n\n    return maximum\n\nprint(f"max([3, 7, 2, 9, 4]) = {find_max([3, 7, 2, 9, 4])}")\n\n# Challenge 5: Palindrome Check\nprint("\\n=== Challenge 5: Palindrome ===")\ndef is_palindrome(s):\n    s = s.lower().replace(" ", "")\n    return s == s[::-1]\n\nfor word in ["racecar", "hello", "madam", "Python"]:\n    print(f"  '{word}' → {is_palindrome(word)}")`,
        questions: ["Explain your approach to FizzBuzz step by step.", "How do you extract the last digit of a number? (Hint: modulo)", "Write a function that checks if a number is prime.", "What edge cases should you consider for the palindrome check?"]
    },

    13: {
        content: `### Day 13: Functions — Defining, Calling, and Return Values\n\n**What is a Function?**\nA function is a reusable block of code that performs a specific task. Functions make code organized, readable, and testable.\n\n**Syntax:**\n\`\`\`python\ndef function_name(parameters):\n    \"\"\"Docstring — explains what the function does\"\"\"\n    # function body\n    return result\n\`\`\`\n\n**Key Concepts:**\n- **Parameters:** Variables listed in the function definition\n- **Arguments:** Actual values passed when calling the function\n- **Return:** Sends a value back to the caller. Without return, function returns None\n- **Docstring:** First line string that documents the function\n\n**Why Functions Matter in Product Companies:**\n- Code reusability — write once, use everywhere\n- Easier testing — test each function independently\n- Better collaboration — clear function interfaces\n- Code review — reviewers understand modular code faster`,
        code: `# Day 13: Functions — Define, Call, Return\n\n# Basic function\ndef greet(name):\n    \"\"\"Returns a greeting message\"\"\"\n    return f"Hello, {name}! Welcome aboard."\n\nprint(greet("Ruban"))\nprint(greet("Alice"))\n\n# Function with default parameter\ndef calculate_tax(amount, rate=0.18):\n    \"\"\"Calculate tax with default GST rate of 18%\"\"\"\n    tax = amount * rate\n    total = amount + tax\n    return tax, total  # Return multiple values\n\ntax, total = calculate_tax(1000)\nprint(f"\\nTax: ₹{tax}, Total: ₹{total}")\n\ntax, total = calculate_tax(1000, 0.05)  # Custom rate\nprint(f"Tax (5%): ₹{tax}, Total: ₹{total}")\n\n# Function as a tool\ndef is_even(n):\n    return n % 2 == 0\n\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8]\nevens = [n for n in numbers if is_even(n)]\nprint(f"\\nEven numbers: {evens}")\n\n# Real-world example: Data validation\ndef validate_email(email):\n    \"\"\"Simple email validation\"\"\"\n    if "@" not in email:\n        return False, "Missing @"\n    if "." not in email.split("@")[1]:\n        return False, "Missing domain"\n    return True, "Valid"\n\nemails = ["user@gmail.com", "invalid-email", "test@com"]\nfor email in emails:\n    valid, msg = validate_email(email)\n    status = "✅" if valid else "❌"\n    print(f"  {status} {email}: {msg}")`,
        questions: ["What is the difference between parameters and arguments?", "What does a function return if there is no return statement?", "Why should every function have a docstring?", "Write a function that takes a list of numbers and returns both the minimum and maximum."]
    },

    14: {
        content: `### Day 14: Arguments — *args, **kwargs, and Default Parameters\n\n**Default Parameters:**\nGive parameters a default value so they become optional:\n\`\`\`python\ndef greet(name, greeting="Hello"):\n    print(f"{greeting}, {name}!")\n\`\`\`\n\n**Positional vs Keyword Arguments:**\n- Positional: \`greet("Ruban", "Hi")\` — order matters\n- Keyword: \`greet(greeting="Hi", name="Ruban")\` — order doesn't matter\n\n***args — Variable Positional Arguments:**\nAccepts any number of positional arguments as a tuple:\n\`\`\`python\ndef total(*args):\n    return sum(args)\ntotal(1, 2, 3, 4, 5)  # 15\n\`\`\`\n\n****kwargs — Variable Keyword Arguments:**\nAccepts any number of keyword arguments as a dictionary:\n\`\`\`python\ndef user_info(**kwargs):\n    for key, val in kwargs.items():\n        print(f"{key}: {val}")\n\`\`\`\n\n**Parameter Order:** \`def func(positional, default=val, *args, **kwargs)\``,
        code: `# Day 14: *args, **kwargs, and Default Parameters\n\n# Default parameters\ndef power(base, exponent=2):\n    return base ** exponent\n\nprint(f"3² = {power(3)}")        # uses default: 9\nprint(f"2³ = {power(2, 3)}")     # custom: 8\n\n# *args — variable positional arguments\ndef calculate_average(*args):\n    \"\"\"Calculate average of any number of values\"\"\"\n    if not args:\n        return 0\n    return sum(args) / len(args)\n\nprint(f"\\nAvg(10, 20, 30) = {calculate_average(10, 20, 30)}")\nprint(f"Avg(5, 15) = {calculate_average(5, 15)}")\n\n# **kwargs — variable keyword arguments\ndef create_profile(**kwargs):\n    \"\"\"Create a user profile from keyword arguments\"\"\"\n    print("\\n--- User Profile ---")\n    for key, value in kwargs.items():\n        print(f"  {key}: {value}")\n\ncreate_profile(name="Ruban", role="ML Engineer", city="Chennai", skills="Python, SQL")\n\n# Combining all types\ndef log_event(event_type, *tags, severity="INFO", **metadata):\n    print(f"\\n[{severity}] {event_type}")\n    if tags:\n        print(f"  Tags: {', '.join(tags)}")\n    for k, v in metadata.items():\n        print(f"  {k}: {v}")\n\nlog_event("Model Training", "ml", "production",\n          severity="WARNING",\n          model="XGBoost", accuracy=0.94, dataset="customers.csv")`,
        questions: ["What is the difference between *args and **kwargs?", "In what order must you define parameters: positional, default, *args, **kwargs?", "Write a function that accepts any number of numbers and returns both the sum and count.", "Why are default parameters useful? Give a real-world example."]
    },

    15: {
        content: `### Day 15: Scope — Global vs Local Variables and Closures\n\n**Variable Scope:**\nScope determines where a variable can be accessed.\n\n**Local Scope:** Variables created inside a function. Only accessible within that function.\n\n**Global Scope:** Variables created outside all functions. Accessible everywhere but shouldn't be modified inside functions.\n\n**The \`global\` Keyword:**\n\`\`\`python\ncount = 0\ndef increment():\n    global count\n    count += 1\n\`\`\`\nAvoid \`global\` — it makes code harder to debug. Pass values as parameters instead.\n\n**LEGB Rule (Lookup Order):**\n1. **L**ocal — inside the current function\n2. **E**nclosing — in outer (enclosing) functions\n3. **G**lobal — at the module level\n4. **B**uilt-in — Python's built-in names (print, len, etc.)\n\n**Closures:**\nA function that remembers variables from its enclosing scope, even after the outer function returns.`,
        code: `# Day 15: Scope — Global, Local, and Closures\n\n# Local vs Global\nx = "I am GLOBAL"\n\ndef show_scope():\n    x = "I am LOCAL"\n    print(f"Inside function: {x}")  # LOCAL\n\nshow_scope()\nprint(f"Outside function: {x}")     # GLOBAL\n\n# Without local variable, reads global\ny = 100\ndef read_global():\n    print(f"\\nReading global y: {y}")  # reads global\n\nread_global()\n\n# LEGB Rule demo\nprint("\\n=== LEGB Rule ===")\nname = "Global"\n\ndef outer():\n    name = "Enclosing"\n    def inner():\n        name = "Local"\n        print(f"  Inner sees: {name}")  # Local\n    inner()\n    print(f"  Outer sees: {name}")  # Enclosing\n\nouter()\nprint(f"  Module sees: {name}")  # Global\n\n# Closure — function that remembers its enclosing scope\nprint("\\n=== Closure ===")\ndef make_multiplier(factor):\n    \"\"\"Returns a function that multiplies by factor\"\"\"\n    def multiply(number):\n        return number * factor\n    return multiply\n\ndouble = make_multiplier(2)\ntriple = make_multiplier(3)\n\nprint(f"double(5) = {double(5)}")   # 10\nprint(f"triple(5) = {triple(5)}")   # 15\n\n# Practical closure: counter\ndef make_counter():\n    count = [0]  # mutable object to track count\n    def increment():\n        count[0] += 1\n        return count[0]\n    return increment\n\ncounter = make_counter()\nprint(f"\\nCounter: {counter()}, {counter()}, {counter()}")  # 1, 2, 3`,
        questions: ["What is the difference between local and global scope?", "What is the LEGB rule? Explain each letter.", "Why should you avoid using the 'global' keyword?", "What is a closure? Write a simple closure function."]
    },

    16: {
        content: `### Day 16: DSA — Arrays and Two-Pointer Technique (LeetCode Easy)\n\n**Why DSA for AI/ML Engineers?**\nProduct companies test DSA in coding rounds — even for ML roles. You must pass the coding interview before discussing ML.\n\n**Two-Pointer Technique:**\nUse two pointers that move towards each other or in the same direction to solve array problems efficiently.\n\n**When to Use Two-Pointer:**\n- Sorted array problems\n- Finding pairs that sum to a target\n- Removing duplicates in-place\n- Reversing arrays/strings\n\n**Time Complexity:** O(n) — much better than brute force O(n²)\n\n**Pattern:**\n1. Initialize left pointer at start, right pointer at end\n2. Compare values at both pointers\n3. Move pointers based on comparison\n4. Stop when pointers cross\n\n**Practice:** Solve 2-3 LeetCode Easy problems:\n- Two Sum II (sorted array)\n- Valid Palindrome\n- Remove Duplicates from Sorted Array`,
        code: `# Day 16: DSA — Two-Pointer Technique\n\n# Problem 1: Two Sum on Sorted Array\ndef two_sum_sorted(nums, target):\n    \"\"\"Find two numbers that sum to target. O(n) time, O(1) space\"\"\"\n    left, right = 0, len(nums) - 1\n    while left < right:\n        current_sum = nums[left] + nums[right]\n        if current_sum == target:\n            return [left, right]\n        elif current_sum < target:\n            left += 1\n        else:\n            right -= 1\n    return [-1, -1]\n\nprint("=== Two Sum Sorted ===")\nnums = [1, 3, 5, 7, 9, 11]\nresult = two_sum_sorted(nums, 12)\nprint(f"Target 12: indices {result} → {nums[result[0]]}+{nums[result[1]]}")\n\n# Problem 2: Valid Palindrome\ndef is_palindrome(s):\n    \"\"\"Check palindrome ignoring non-alphanumeric chars\"\"\"\n    s = ''.join(c.lower() for c in s if c.isalnum())\n    left, right = 0, len(s) - 1\n    while left < right:\n        if s[left] != s[right]:\n            return False\n        left += 1\n        right -= 1\n    return True\n\nprint("\\n=== Palindrome Check ===")\nfor text in ["racecar", "hello", "A man a plan a canal Panama"]:\n    print(f"  '{text}' → {is_palindrome(text)}")\n\n# Problem 3: Remove Duplicates from Sorted Array\ndef remove_duplicates(nums):\n    \"\"\"Remove duplicates in-place, return new length\"\"\"\n    if not nums:\n        return 0\n    write = 1\n    for read in range(1, len(nums)):\n        if nums[read] != nums[read - 1]:\n            nums[write] = nums[read]\n            write += 1\n    return write\n\nprint("\\n=== Remove Duplicates ===")\narr = [1, 1, 2, 2, 3, 4, 4, 5]\nlength = remove_duplicates(arr)\nprint(f"Unique: {arr[:length]}, Length: {length}")`,
        questions: ["Explain the two-pointer technique. When is it useful?", "What is the time complexity of two-pointer vs brute force for Two Sum?", "Write a function to reverse an array in-place using two pointers.", "How would you find if a sorted array has any pair with a given difference?"]
    },

    17: {
        content: `### Day 17: OOP — Classes, Objects, and the self Keyword\n\n**What is OOP?**\nObject-Oriented Programming organizes code around "objects" that combine data (attributes) and behavior (methods). Real-world example: a Car object has attributes (color, speed) and methods (start, stop).\n\n**Class vs Object:**\n- **Class:** A blueprint/template (like a cookie cutter)\n- **Object:** An instance created from the class (like the cookie)\n\n**The \`self\` Keyword:**\n\`self\` refers to the current instance of the class. It lets each object keep its own data:\n\`\`\`python\nclass Dog:\n    def __init__(self, name):\n        self.name = name  # self.name belongs to THIS dog\n\`\`\`\n\n**Why OOP Matters for ML Engineers:**\n- scikit-learn: Every model is a class with \`.fit()\` and \`.predict()\` methods\n- PyTorch: Models inherit from \`nn.Module\`\n- Real codebases: You'll read and write class-based code daily`,
        code: `# Day 17: Classes, Objects, and self\n\n# Basic class\nclass Dog:\n    # Class attribute (shared by all dogs)\n    species = "Canis lupus familiaris"\n    \n    def __init__(self, name, breed, age):\n        # Instance attributes (unique to each dog)\n        self.name = name\n        self.breed = breed\n        self.age = age\n    \n    def bark(self):\n        return f"{self.name} says: Woof!"\n    \n    def info(self):\n        return f"{self.name} ({self.breed}, {self.age} years)"\n\n# Create objects\ndog1 = Dog("Buddy", "Labrador", 3)\ndog2 = Dog("Max", "German Shepherd", 5)\n\nprint(dog1.bark())    # Buddy says: Woof!\nprint(dog2.info())    # Max (German Shepherd, 5 years)\nprint(f"Species: {Dog.species}")  # class attribute\n\n# Real-world: ML Model Tracker\nprint("\\n=== ML Experiment Tracker ===")\nclass Experiment:\n    def __init__(self, name, model_type):\n        self.name = name\n        self.model_type = model_type\n        self.metrics = {}\n        self.is_complete = False\n    \n    def log_metric(self, metric_name, value):\n        self.metrics[metric_name] = round(value, 4)\n    \n    def complete(self):\n        self.is_complete = True\n    \n    def summary(self):\n        status = "✅ Complete" if self.is_complete else "🔄 Running"\n        print(f"\\n--- {self.name} ({status}) ---")\n        print(f"Model: {self.model_type}")\n        for k, v in self.metrics.items():\n            print(f"  {k}: {v}")\n\n# Use the tracker\nexp = Experiment("churn_prediction_v1", "RandomForest")\nexp.log_metric("accuracy", 0.8734)\nexp.log_metric("f1_score", 0.8221)\nexp.log_metric("auc", 0.9102)\nexp.complete()\nexp.summary()`,
        questions: ["What is the difference between a class and an object?", "What is 'self' and why is every method's first parameter 'self'?", "What is the difference between a class attribute and an instance attribute?", "Create a class 'BankAccount' with methods deposit(), withdraw(), and get_balance()."]
    },

    18: {
        content: `### Day 18: OOP — The __init__ Constructor and Instance Methods\n\n**The __init__ Method:**\n\`__init__\` is the constructor — it runs automatically when you create an object. Use it to initialize the object's attributes.\n\n**Instance Methods:**\nFunctions defined inside a class that operate on the object's data using \`self\`.\n\n**Naming Conventions:**\n- \`__method__\`: Dunder (double underscore) methods — Python's special methods\n- \`_method\`: Private by convention (can still be accessed)\n- \`method\`: Public method\n\n**Common Dunder Methods:**\n- \`__init__\`: Constructor\n- \`__str__\`: String representation for print()\n- \`__repr__\`: Developer-facing string representation\n- \`__len__\`: Called by len()\n- \`__eq__\`: Called by ==`,
        code: `# Day 18: __init__ Constructor and Instance Methods\n\nclass Student:\n    \"\"\"Represents a student with grades\"\"\"\n    \n    def __init__(self, name, student_id):\n        self.name = name\n        self.student_id = student_id\n        self.grades = []  # Initialize empty list\n    \n    def add_grade(self, subject, score):\n        \"\"\"Add a grade for a subject\"\"\"\n        self.grades.append({"subject": subject, "score": score})\n    \n    def get_average(self):\n        \"\"\"Calculate average grade\"\"\"\n        if not self.grades:\n            return 0\n        return sum(g["score"] for g in self.grades) / len(self.grades)\n    \n    def get_highest(self):\n        \"\"\"Get highest scoring subject\"\"\"\n        if not self.grades:\n            return None\n        return max(self.grades, key=lambda g: g["score"])\n    \n    def __str__(self):\n        \"\"\"Called by print()\"\"\"\n        return f"Student({self.name}, ID: {self.student_id}, Avg: {self.get_average():.1f})"\n    \n    def __repr__(self):\n        \"\"\"Developer representation\"\"\"\n        return f"Student('{self.name}', '{self.student_id}')"\n    \n    def __len__(self):\n        \"\"\"Number of grades\"\"\"\n        return len(self.grades)\n\n# Usage\nstudent = Student("Ruban", "AI2026")\nstudent.add_grade("Python", 92)\nstudent.add_grade("SQL", 88)\nstudent.add_grade("ML", 95)\nstudent.add_grade("Statistics", 78)\n\nprint(student)  # Uses __str__\nprint(f"Number of subjects: {len(student)}")  # Uses __len__\nprint(f"Highest: {student.get_highest()}")\n\n# repr in debugging\nprint(f"\\nRepr: {repr(student)}")  # Uses __repr__\n\n# Multiple objects\nstudents = [\n    Student("Alice", "A001"),\n    Student("Bob", "B002"),\n]\nstudents[0].add_grade("Python", 90)\nstudents[1].add_grade("Python", 85)\n\nfor s in students:\n    print(s)`,
        questions: ["What is __init__ and when does it run?", "What is the difference between __str__ and __repr__?", "What happens if you print an object without defining __str__?", "Write a class 'ShoppingCart' with add_item(), remove_item(), and total() methods."]
    },

    19: {
        content: `### Day 19: OOP — Inheritance, Polymorphism, and super()\n\n**Inheritance:**\nA child class inherits attributes and methods from a parent class. Promotes code reuse.\n\`\`\`python\nclass Animal:        # Parent\n    pass\nclass Dog(Animal):   # Child inherits from Animal\n    pass\n\`\`\`\n\n**super():**\nCalls the parent class's method from the child class. Most commonly used in __init__.\n\n**Polymorphism:**\nDifferent classes can have methods with the same name but different behavior. Example: both Dog and Cat have a \`speak()\` method, but Dog barks and Cat meows.\n\n**Method Overriding:**\nThe child class redefines a parent's method to change its behavior.\n\n**isinstance() and issubclass():**\n- \`isinstance(obj, Class)\` — check if obj is an instance of Class\n- \`issubclass(Child, Parent)\` — check inheritance`,
        code: `# Day 19: Inheritance, Polymorphism, super()\n\n# Parent class\nclass Model:\n    def __init__(self, name, version="1.0"):\n        self.name = name\n        self.version = version\n        self.is_trained = False\n    \n    def train(self, data):\n        self.is_trained = True\n        print(f"  Training {self.name} v{self.version}...")\n    \n    def predict(self, x):\n        if not self.is_trained:\n            raise Exception("Model not trained!")\n        return None  # Base model returns nothing\n\n# Child classes\nclass LinearModel(Model):\n    def __init__(self, name):\n        super().__init__(name)  # Call parent's __init__\n        self.coefficients = []\n    \n    def train(self, data):  # Override\n        super().train(data)  # Call parent's train first\n        self.coefficients = [0.5, 1.2, -0.3]\n        print(f"  Learned coefficients: {self.coefficients}")\n    \n    def predict(self, x):\n        super().predict(x)\n        return sum(c * xi for c, xi in zip(self.coefficients, x))\n\nclass TreeModel(Model):\n    def __init__(self, name, max_depth=5):\n        super().__init__(name)\n        self.max_depth = max_depth\n    \n    def train(self, data):\n        super().train(data)\n        print(f"  Built tree with max_depth={self.max_depth}")\n    \n    def predict(self, x):\n        super().predict(x)\n        return 1 if sum(x) > 0 else 0\n\n# Polymorphism — same interface, different behavior\nprint("=== Polymorphism ===")\nmodels = [LinearModel("LinearReg"), TreeModel("DecisionTree", max_depth=3)]\n\nfor model in models:\n    model.train([1, 2, 3])  # Same method call\n    result = model.predict([1.0, 2.0, 3.0])\n    print(f"  Prediction: {result}\\n")\n\n# isinstance check\nprint(f"LinearModel is a Model? {isinstance(models[0], Model)}")`,
        questions: ["What is inheritance? Give a real-world example.", "What does super() do and why is it important?", "What is polymorphism? How does it work in Python?", "Create a parent class Shape with method area(), and child classes Circle and Rectangle that override area()."]
    },

    20: {
        content: `### Day 20: OOP — Encapsulation and Property Decorators\n\n**Encapsulation:**\nHiding internal details and providing a public interface. Prevents external code from accidentally corrupting an object's state.\n\n**Access Levels in Python:**\n- \`public\`: \`self.name\` — accessible everywhere\n- \`protected\`: \`self._name\` — convention: "don't touch from outside"\n- \`private\`: \`self.__name\` — name-mangled, harder to access externally\n\n**@property Decorator:**\nLets you define getter/setter methods that look like regular attributes:\n\`\`\`python\nclass Circle:\n    @property\n    def area(self):\n        return 3.14 * self._radius ** 2\n    \n    @area.setter\n    def area(self, value):\n        # can add validation here\n\`\`\`\n\n**Why Use Properties?**\n- Add validation when setting values\n- Compute derived values on the fly\n- Change internal implementation without breaking external code`,
        code: `# Day 20: Encapsulation and @property\n\nclass BankAccount:\n    def __init__(self, owner, initial_balance=0):\n        self.owner = owner          # public\n        self._balance = initial_balance  # protected\n        self.__pin = "1234"         # private (name-mangled)\n    \n    @property\n    def balance(self):\n        \"\"\"Getter — read balance safely\"\"\"\n        return self._balance\n    \n    @balance.setter\n    def balance(self, value):\n        \"\"\"Setter — validate before setting\"\"\"\n        if value < 0:\n            raise ValueError("Balance cannot be negative!")\n        self._balance = value\n    \n    def deposit(self, amount):\n        if amount <= 0:\n            print("  ❌ Deposit must be positive")\n            return\n        self._balance += amount\n        print(f"  ✅ Deposited ₹{amount}. New balance: ₹{self._balance}")\n    \n    def withdraw(self, amount):\n        if amount > self._balance:\n            print("  ❌ Insufficient funds")\n            return\n        self._balance -= amount\n        print(f"  ✅ Withdrew ₹{amount}. New balance: ₹{self._balance}")\n\n# Usage\nprint("=== Bank Account ===")\nacc = BankAccount("Ruban", 5000)\nprint(f"Balance: ₹{acc.balance}")  # Uses @property getter\nacc.deposit(2000)\nacc.withdraw(1500)\nacc.withdraw(10000)  # Should fail\n\n# Temperature converter with property\nprint("\\n=== Temperature ===")\nclass Temperature:\n    def __init__(self, celsius):\n        self._celsius = celsius\n    \n    @property\n    def celsius(self):\n        return self._celsius\n    \n    @celsius.setter\n    def celsius(self, value):\n        if value < -273.15:\n            raise ValueError("Below absolute zero!")\n        self._celsius = value\n    \n    @property\n    def fahrenheit(self):\n        return (self._celsius * 9/5) + 32\n\ntemp = Temperature(37)\nprint(f"{temp.celsius}°C = {temp.fahrenheit}°F")\ntemp.celsius = 100\nprint(f"{temp.celsius}°C = {temp.fahrenheit}°F")`,
        questions: ["What is encapsulation and why is it important?", "What is the difference between _variable and __variable in Python?", "What is the @property decorator? When should you use it?", "Write a class with a property that validates input (e.g., age must be between 0 and 150)."]
    },
};
